contratacionespublicas:
  opciones:
    activo: true
    descripcion: Módulo de Contrataciones Públicas Bienes y Servicios
    imagen: licitaciones.gif
    nombre: Contrataciones Públicas Bienes y Servicios
    urls:
      default:
        modulo: licitaciones.php
        modulo_dev: licitaciones_dev.php
      Catálogo Presupuestario del Ente:
        #LISTO
        modulo: presupuesto.php
        modulo_dev: presupuesto_dev.php
      Partidas para la Contratacion de Obras particulares del Ente:
        #LISTO
        modulo: obras.php
        modulo_dev: obras_dev.php
      Artículos SNC:
        #LISTO
        modulo: compras.php
        modulo_dev: compras_dev.php
      Catálogo de Artículos/Servicios del Ente:
        #LISTO
        modulo: compras.php
        modulo_dev: compras_dev.php
      Unidades de Medida:
        #LISTO
        modulo: obras.php
        modulo_dev: obras_dev.php
      Fuente de Financiamiento:
        #LISTO
        modulo: formulacion.php
        modulo_dev: formulacion_dev.php
      División Territorial:
        #LISTO
        modulo: obras.php
        modulo_dev: obras_dev.php
      Solicitud de Contratación:
        #LISTO
        modulo: obras.php
        modulo_dev: obras_dev.php
      Cambiar Contraseña:
        modulo: autenticacion.php
        modulo_dev: autenticacion_dev.php
      Reportes:
        absoluta: reportes/reportes/licitaciones
    imagenes:
      default: OperatorClass.png
  menu:
    Definiciones Generales:
      Ente Contratante:                                         licdefemp
      Ley de Contrataciones Públicas:                           licleycon
      Catálogos Requeridos:
        Normas COVENIN:                                         licnorcov
        Partidas para la Contratacion de Obras particulares del Ente:  oycdefpar
        (*)Presupuesto ONAPRE:                                  preonapre
        Catálogo Presupuestario del Ente:                       pretitpre
        Artículos SNC:                                          almdefcatsnc
        Catálogo de Artículos/Servicios del Ente:               AlmRegArt
        Tipo de Empresa:                                        lictipemp
        Prioridad de Contratación:                              licpriocon
      Modalidad de Contratación:                                lictiplic
      Declaratoria Modalidad de Contratación:                   licsicact
      Unidades de Medida:                                       oycdefuni
      Solicitud de Contratación:                                oycclacomp
      Mecanismos de Concurso:                                   licmeccon
      #Unidad Administrativa:                                    licuniadm
      Unidad Ejecutora Local:
        Tipo:                                                   lictipuniste
        Registro:                                               licuniste
      Integrantes Comisión de Contratación:                     liccomlic
      Fuente de Financiamiento:                                 pretitfin
      División Territorial:
        Pais:                                                   oycdefdivpai
        Estado:                                                 oycdefdivest
        Ciudad:                                                 oycdefdivciu
        Municipio:                                              oycdefdivmun
        Parroquia:                                              oycdefdivpar
        Sector:                                                 oycdefdivsec
      Criterios de Calificación Recaudos y Garantias:
        Legales:                                                licasplegcriterios
        Técnico:                                                licaspteccriterios
        Financieros:                                            licaspfincriterios
        Fianzas/Garantias:                                      liccomres
    Proceso de Contratación:
      Solicitud de Bien/Servicio:
        Presupuesto Base:                                       licprebas
        Memorando Solicitud de Aprobación Egreso:               licmemoran
        Punto de Cuenta Solicitud de Aprobación Egreso:         licptocue
        Requisición/Solicitud de Egresos:                       licsolegr
        Adquisición/Compra Integral:                            liccomint
      Pliego de Condiciones:
        Especificaciones del Pliego de Condiciones:             licplieesp
        Participantes:                                          licemppar
        Aclaratoria/Respuestas:                                 licaclara
        (*)Prorrogas:                                              licprorro
      Oferentes:                                                licempofe
      Ofertas:
        Registro de Ofertas:                                    licregofe
        Analisis de Ofertas:                                    licanaofe
      Recomendación:                                            licrecomen
      Punto de Cuenta/Aprobación Contratación:                  licptocuecon
      Notificación de Adjudicación:                             licnotific
    Declaratorias:
      (**)Presupuesto Base:                                       licaprprebas
      (*)Memorando Solicitud de Egreso:                          licaprprebas
      (*)Requisición:                                            AlmAprSolEgr
      Compra Integral/Pedido:                                 licaprcomint
      (*)Piego de Condiciones:                                   licaprcomint
      (*)Punto de Cuenta Aprobación de Egreso:                   licaprcomint
      (*)Punto de Cuenta Aprobación de Contratación:             licaprcomint
      (*)Aclaratoria/Respuestas:                                 licaprcomint
      (*)Prorroga:                                               licaprcomint
      (*)Medidas:                                                licaprcomint
    Reportes:
      Definiciones:                                             lic
    Mantenimiento:
      Cambiar Contraseña:                                       cambiopasswd
