nomina:
  opciones:
    activo: true #true/false
    descripcion: Módulo de Nómina
    imagen: nomina.gif
    nombre: Recursos Humanos
    urls:
      Cambiar Contraseña:
        modulo: autenticacion.php
        modulo_dev: autenticacion_dev.php
      default:
        modulo: nomina.php
        modulo_dev: nomina_dev.php
      Reportes:
        absoluta: reportes/reportes/nomina
    imagenes:
      default: OperatorClass.png
  menu:
    Definiciones Específicas:
      Incapacidades:                                                 Nominc
      Institución:                                                   NomDefEspGen
      Tipos Nóminas:                                                 NomDefEspTipNom
      Conceptos:                                                     NomDefEspCon
      Niveles Organizacionales:                                      NomDefEspNivOrg
      Ubicaciones Físicas:                                            nomdefubi
      Niveles de Estudio:                                            NomDefEspNivEdu
      Cargos:                                                        NomDefEspCar
      #Cargos Colaterales:                                            NomDefEspCargosCol
      Definición de Conceptos Variables:                             NomDefEspMovPer
      Variables:                                                     NomDefEspVar
      Bancos:                                                        NomDefEspBan
      Profesiones:                                                   NomDefEspProFes
      Perfiles:                                                      NomDefEspPerFil
      Tipos de Parientes:                                            NomDefEspPar
      Guarderías:                                                    NomDefEspGuarde
      Tipos de Gastos:                                               NomDefTipGas
      #Tipo de Personal:                                              NomTipCar
      Tipo de Empleado:                                              nomtipemp
      Motivos de Faltas y/o Permisos:                                NomDefEspMotFalPre
      Estatus del Empleado:                                          nomdefestemp
      Situacion del Empleado:                                        nomdefespsitemp
      Definición de Condición Contractual:                           NomDefEspGruLab
      #Definición Seguro HCM:                                         NomDefEspSegHcm
      #Definición de Acumulador de Conceptos:                         Nomacumulacpt
      Conceptos para Reportes:                                       NomDefEspConSue
      Conceptos para el Salario Integral:                            NomConceptosSalarioIntegral
      Conceptos para el Sueldo:                                      NomConceptosSueldo
      Conceptos para las Primas:                                     NomConceptosPrimas
      Parametros Especiales para el Calculo de las Primas:           NomDefEspPrimas
      Conceptos de Compensación por Nómina:                          NomConceptosCompensacion
      Conceptos de Ahorro Habitacional:                              NomDefConAho
      Conceptos para el Fondo de Jubilación y Pensiones:             NomDefConFon
      Definición de Jornadas Laborales:                              NomDefEspJorLab
      Jornadas Laborales por Empleado:                               NomJorLabInd
      Definición de Concepto de Cesta Tickets:                       NomDefEspCesTic
      Tipos de Retiros:                                              NomDefTipRet
      Definición de Conceptos para Dias Adicionales:                 NomDefDiaAdicNom
      Conceptos para el ISLR:                                        NomDefEspISLR
      Motivos de Cambios de Cargos:                                  NomDefEspMotCamCar
      #Embargos:
        #Registro de Juzgados:                                        NomDefJuz
        #Registro de Beneficiarios por Embargos:                      NomDefBenEmb
        #Registro de Embargos:                                        NomRegEmb
      Definición de Retenciones y Aportes:
        Retenciones y Aportes:                                       NomDefAportes
        Conceptos para Aportes:                                      NomDefConAportes
        Conceptos para Retenciones:                                  NomDefConRetencion
        #Conceptos de Sueldo para Aportes:                            nomdefconsuelaportes
        #Conceptos de Sueldo para Retención:                          nomdefconsuelretenciones
      División Territorial:
        Estados:                                                     NomDefEspPai
        Municipios:                                                  NomDefEspEst
        Parroquias:                                                  NomDefEspCiu
    Personal:
      Datos Personales:                                              NomHojInt
      Tipo de Cargos:                                                NomTipCar
      #Categorías Presupuestarias para Formular Cargos:              ForDefCatPre
      #Nominas a Formular:                                           ForNomFor
      #Formulas de Conceptos:                                        ForCalCon
      Tipo de Dedicación:                                            NomTipDed
      #Tipo de Categoria:                                             NomTipCat
      #Asignación de Conceptos a Cargos:                             ForAsoConCar
      Tabla de Sueldos por Grado y Paso:                             NomComOCP
      Asignación de Cargos y Conceptos a Empleados:                  NomAsiCarConNom
      #Asignación de Cargos a Empleados en lote:                     NomAsiCarEmpLot
      Cambio de Nómina y Cargos a Empleados:                         nomcamnomcar
      #Formulación de Cargos Presupuestados:                         ForPreGasPer
      #Archivo de Elegibles:                                         nomhojint
      #Datos Personales:                                             NomPerEleDatPer
      #Información Familiar:                                         NomPerEleInfFam
      #Información Curricular:                                       NomPerEleInfCur
      #Experiencia Laboral:                                          NomPerEleExpLab
    #Capacitación y Adiestramiento:
      #Definiciones Especificas:
        #Area del Curso:                                              NomDefAreCur
        #Tipo de Curso:                                               NomDefTipCur
        #Títulos del Curso:                                           NomDefTitCur
        #Definición del Curso:                                        NomDefCur
      #Adiestramiento:
        #Inscripción al Curso:                                        NomInsCur
        #Asistencia al Curso:                                         NomAsiCur
        #Evaluar Curso:                                               NomNotCur
    #Evalución y Desempeño:
      #Definicion de Rangos e Actuacion:                              NomDefRan
      #Control de Competencias:
        #Definiciones Especificas:
          #Valores Institucionales:                                   NomDefValIns
          #Niveles:                                                   NomDefNiv
          #Valores por Nivel:                                         NomValNiv
        #Evaluación:
          #Datos del Evaluado:                                        NomDatEva
          #Control de Competencia:                                    NomEvaConCom
      #Control de Gestion por Resultados:
        #Definiciones Especificas:
          #Objetivos:                                                 NomDefObj
          #Indicadores:                                               NomDefInd
          #Niveles:                                                   NomDefNiv2
          #Indicadores por Nivel:                                     NomIndNiv
        #Evaluación:
          #Relación de Objetivos Individuales:                        NomRelObjInd
          #Evaluación de los Objetivos:                               NomEvaEmpObj
    Faltas y/o Permisos:
      Permisos:                                                      NomFalPerPer
      Salidas:                                                       NomFalPerSal
      Llegadas:                                                      NomFalPerLle
      Registro de Días Extras:                                       NomDiaExt
      Registro de Faltas y/o Permisos Por Nómina en Lote:            NomFalPerLot
      Registro de Faltas y/o Permisos Por Empleado:                  NomFalPerEmp
      Registro de Días Extras Por Nómina en Lote:                    NomDiaExtLabLot
    Vacaciones:
      Parámetros para el Registro y Control de Vacaciones:           VacDefGen
      Definición de Jornada Laboral:               VacDiasBonoVac
      Tabla para los Días de Disfrute:                               VacDiaDis
      Tabla para los Días Feriados:                                  VacDiaFer
      Registro de Vacaciones Disfrutadas:                            VacHistorico
      Registro de Vacaciones Disfrutadas en Lote:                    VacHistorico_Lote
      #Registro de Vacaciones Colectivas:                             Vaccolecti
      Registro de Solicitud de Vacaciones:                           VacSALIDAS
      #Registro y Control de Vacaciones:                             VacRegSalVac
      Liquidación de Vacaciones Por Egreso:                          VacLiquidacion
    Prestaciones:
      Definición de Parámetros para las Prestaciones Sociales:
        Tipos de Contratos Colectivos:                               PresNomTipCon
        Registro de Tipos de Asignaciones:                           presNomAsiConPre
        Definición Especial de Bono de Fin de Año:                   nomdefespdiabonfinano
        Definición Presupuestaria de Liquidación:                    presNomDefPre
        Definiciones Especiales para Prestaciones:                   NomDefEspParPre
        Definiciones de Clausulas para Prestaciones:                 NomDefEspClauDet
        Definición de Periodos por Meses:                            presNomSemMes
        Parámetros para el Salario Integral:                         presnomparsalint
      Registros Útiles para el Cálculo de Prestaciones Sociales:
        Asignación de Trab. para Prestaciones Por Contr. Colect:     presNomAsiTrabCont
        Registro de Tasas de Interes Periodicas:                     presNomIntFecRef
        Registro de Salario Integral por Contrato:                   presNomRegSalInt
        Registro de Salario Integral por Contrato Individual:        presNomRegSalIntInd
      Registro Histórico de Anticipos Otorgados:                     PresNomRegHisAntPre
      Registro Histórico de Adelanto de Intereses de Prestaciones:   PresNomRegHisAdeint
      Solicitud de Anticipo Sobre Prestaciones:                      PresNomAntPre
      Solicitud de Anticipo Sobre Intereses de Prestaciones:         PresNomAdeInt
      Cálculo de Antiguedad:                                         presNomCalIntPre
      Cálculo de Antiguedad en Lote:                                         presNomCalIntPreLot
      Liquidación Final de Prestaciones:                             presnomliquidacion
      #Importar Datos Prestaciones Sociales:                         ImportarPrestaciones
    Asignaciones Generales para el Cálculo de Nómina:
      Asignación de Conceptos por Categ. Presup. Espec.:             AsignarConceptosCategoria
      Asignación de Conceptos a Nómina:                              AsignarConceptosNomina
      Asignación de Cargos a Nómina:                                 NomDefEspAsiCarTipNomLot
      Asignación de Conceptos a Empleados:                           NomNomAsiConNom
      Asignación de Cuentas Bancarias por Empleado:                  EmpleadosBanco
      Asignación Modalidad Pago Cesta Ticket a Empl por Nómina:      ModalidadCestaTicketEmpleados
      Asignación de Categorias por Empleados:                        AsignarCategoriasConceptosxEmpleado
      Asignar  Partidas a un Concepto por Nomina:                    nomcodprenom
      Asignación de Partidas a Conceptos:                            asignarpartidasconceptos
    Movimientos de Nómina:
      Movimientos Por Concepto:                                      NomNomMovNomCon
      Movimientos Por Concepto y Cargos:                             NomNomMovNomConCar
      Movimientos Por Empleado:                                      NomNomMovNomEmp
      #Modificar Monto/cantidad a Conceptos Según Formula:           ModificarMontoConcepto
    Nominas Especiales:
      Definición:                                                    NomEspDefinicion
      Conceptos:                                                     NomEspConceptos
      Cálculo:                                                       NomEspCalculo
      Cierre de Nóminas Especiales:                                 NomNomCieNomEsp
    Cálculos de Nomina:
      Cálculo de Conceptos - Formulación:                            NomCalCon
      Cálculo de Nómina:                                             NomNomCalNom
      Cálculo de Nómina por Empleados:                               NomNomCalNomInd
      Cierre de Nómina:                                              NomNomCieNom
    Prestamos:
      Tipos de Prestamos:                                            NomDefEspTipPre
      Prestamos:                                                     NomPerPrestamos
      Movimientos de Prestamos:                                      NomPerHisPre
    Reportes:
    Mantenimiento:
      Cambiar Contraseña:                                     cambiopasswd
