generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Casolart
    theme:            default
    fields:
      reqart: { name: Número Solicitud, params: maxlength=8}
      desreq: { name: Descripción, params: maxlength=20}
      fecreq: { name: Fecha, params: date_format='dd/MM/yyyy'}
      articulo: { name: Articulos de la Solicitud}
      actsolegr: { name: Actualizar Solicitud}
      porcostart: { name: Por menor Costo de Artículo}
      pormoncot: { name: Por menor Monto de la Cotización}
      portimeent: { name: Por menor Tiempo de Entrega}
    list:
      title:          Análisis de Cotizaciones
      filters:        [reqart, fecreq]
      display:        [=reqart, desreq, fecreq]
      max_per_page:	  10
      sort:           reqart
      object_actions:
        _edit:        ~

    edit:
      title:         Análisis de Cotizaciones
      display:       [reqart, fecreq , desreq, articulo, actsolegr, porcostart, pormoncot, portimeent]
      fields:
        actsolegr:  {type: checkbox_tag}
        porcostart:  {type: checkbox_tag}
        pormoncot:  {type: checkbox_tag}
        portimeent:  {type: checkbox_tag}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~