default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo Contabilidad
    robots:       index, follow
    description:  Módulo Contabilidad
    keywords:     Módulo Contabilidad
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, observe, ajax, dFilter, contabilidad/confincue ]

  has_layout:     on
  layout:         layout
