generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Atrubros
    theme:            cidesaGenerator

    fields:
      attipayu_id:         { name: Tipo de Donaci贸n, validate: Vstring_1_50, msj_error: Debe seleccionar un Tipo de Ayuda }
      desrub:              { name: Descripci贸n, validate: Vstring_1_100, msj_error: Debe insertar la Descripci贸n del Rubro }
      destipayu:           { name: Rubros }
    list:
        fields:
          desdon:            { name: Rubros, params: size=10 }
        title:          Rubros
        display:        [=desrub, destipayu]
        object_actions:
          _edit:        ~
          _delete:      ~
        filters:        [desrub, attipayu_id]
        fields:
          attipayu_id:
            params: style:width=20px
      max_per_page:   5
      sort:  desrub
    edit:
      title:          Edici贸n de Rubros
      display:
        none:         [attipayu_id, desrub]
        Recaudos:     [ _recaudos ]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~