opciones:                  # Opciones generales
  name:                    b
  eliminar:                false
  tabla:                   forpereje
  ancho:                   400
  anchogrid:               440
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  PerÃ­odo
  tipo:                    t
  nombrecampo:             pereje
  esgrabable:			   true
  html:                    [ size=3 readOnly=true ]
2:       # Columna 2
  titulo:                  Fecha Desde
  tipo:                    t
  nombrecampo:             fecdes2
  esgrabable:			   true
  html:                    [ size=10 readOnly=true ]
3:       # Columna 3
  titulo:                  Fecha Hasta
  tipo:                    t
  nombrecampo:             fechas2
  esgrabable:			   true
  html:                    [ size=10 readOnly=true ]
