opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   viadetcalviatra
  anchogrid:               900
  ancho:                   850
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Check
  tipo:                    k
  nombrecampo:             check
  esgrabable:              true
  html:                    [ ]
2:       # Columna 2
  titulo:                  Rubro
  tipo:                    t
  nombrecampo:             codrub
  oculta:                  true
  esgrabable:              true
  html:                    [ readonly=true ]
3:       # Columna 3
  titulo:                  Descripcion
  tipo:                    t
  nombrecampo:             desrub
  esgrabable:              true
  html:                    [ readonly=true size=50]
4:       # Columna 4
  titulo:                  Numero de Dias a Pagar
  tipo:                    t
  nombrecampo:             numdia
  esgrabable:              true
  html:                    [" size=10 onBlur='ValidarMontoGridv2(this); Calculartotal();'"]
5:       # Columna 5
  titulo:                  Monto Diario a Pagar
  tipo:                    m
  nombrecampo:             mondia
  esgrabable:              true
  html:                    [ size=10 readonly=true]
6:       # Columna 6
  titulo:                  Total A Pagar
  tipo:                    m
  nombrecampo:             montot
  esgrabable:              true
  html:                    [ size=10 readonly=true]
7:       # Columna 7
  titulo:                  Tipo
  tipo:                    t
  nombrecampo:             tipo
  esgrabable:              true
  oculta:                  true
  html:                    [ ]
8:       # Columna 7
  titulo:                  Calculo
  tipo:                    t
  nombrecampo:             calculo
  esgrabable:              false
  oculta:                  true
  html:                    [ ]
9:       # Columna 9
  titulo:                  Diario en $
  tipo:                    m
  nombrecampo:             mondiadol
  esgrabable:              false
  html:                    [ size=10 readonly=true]
#10:       # Columna 10
#  titulo:                  CAMBIO
#  tipo:                    m
#  nombrecampo:             cambio
#  esgrabable:              false
#  html:                    [ size=10 readonly=true]
10:       # Columna 10
  titulo:                  Total en $
  tipo:                    m
  nombrecampo:             montotdol
  esgrabable:              false
  html:                    [ size=10 readonly=true]
