opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   fcusoveh
  ancho:                   250
  anchogrid:               300
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '

1:       # Columna 1
  titulo:                  Campos
  tipo:                    t
  nombrecampo:             campo
  esgrabable:			   true
  html:                    [size="15", readonly=true]
2:       # Columna 2
  titulo:                  Valor
  tipo:                    m
  nombrecampo:             valor
  esgrabable:			   true
  html:                    [size="15", readonly=true]
