generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Lidefemp
    theme:            cidesaGenerator
    fields:
      codemp:    { name: Código, params: size=5 maxlength=3}
      nomemp:    { name: Nombre, params: size=80 maxlength=100}
      diremp:    { name: Dirección, params: size=80 maxlength=100}
      telemp:    { name: Telefono, params: size=20 maxlength=30}
      faxemp:    { name: Fax, params: size=20 maxlength=30}
      emaemp:    { name: Email, params: size=80 maxlength=100}
      unitri:    { name: Monto en Bolívares (Bs.)}
    list:
      title:          Registro Información del Sistema
      display:        [=codemp, nomemp, diremp]
      filters:        [codemp]
      sort            codemp
      object_actions:
        _edit:        ~
      max_per_page:   10
      sort:    codemp
    edit:
      title:          Institución
      display:
        Datos Principales:   [nomemp, diremp, telemp, faxemp, emaemp]
        Valor Actual Unidad Tributaria: [unitri]
      actions:
        _save:        ~