opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   fcactpic
  ancho:                   800
  anchogrid:               800
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código
  tipo:                    t
  nombrecampo:             codact
  esgrabable:			   true
  html:                    [size="15"]
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desact
  esgrabable:              true
  html:                    [size="40", readonly=true ]
3:       # Columna 3
  titulo:                  Ingresos Brutos
  tipo:                    m
  nombrecampo:             monact
  esgrabable:			   true
  esnumerico:              true
  html:                    [size="10"]
4:       # Columna 4
  titulo:                  Exonerable
  tipo:                    t
  nombrecampo:             exonerable
  esgrabable:			   true
  html:                    [size="6", readonly=true ]
5:       # Columna 5
  titulo:                  Exonerada
  tipo:                    c
  nombrecampo:             exoner
  esgrabable:			   true
  html:                    []
6:       # Columna 6
  titulo:                  % Exoneración
  tipo:                    m
  nombrecampo:             porexo
  esgrabable:			   true
  esnumerico:              true
  html:                    [size="10", disabled=true]