generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Liprebas
    theme:            cidesaGenerator
    fields:
      numpre:         { name: Número Presupuesto Base, params: size=10 maxlength=8 onBlur=Correl(this.id) }
      ejepre:         { name: Ejercicio Prespuestario Año, params: style="border:none"}
      codempadm:
        name: Para
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 1
          parametros: getprincipal="getCodempadm" getsecundario="getNomempadm" campoprincipal="codempadm" camposecundario="nomempadm" campobase = "id"
      nomcaradm:      { name: Cargo, params: style=border:none}
      coduniadm:
        name: Unidad 
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 11
          parametros: getprincipal="getCoduniadm" getsecundario="getDesuniadm" campoprincipal="coduniadm" camposecundario="desuniadm" campobase = "id"
      codempeje:
        name: De
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 2
          parametros: getprincipal="getCodempeje" getsecundario="getNomempeje" campoprincipal="codempeje" camposecundario="nomempeje" campobase = "id"
      nomcareje:      { name: Cargo, params: style=border:none}
      coduniste:
        name: Unidad 
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 3
          parametros: getprincipal="getCoduniste" getsecundario="getDesuniste" campoprincipal="coduniste" camposecundario="desuniste" campobase = "id"
      dirunieje:       { name: Dirección, params: readonly=true size=80 style=border:none}
      pai:            { name: Pais, params: readonly=true size=40 style=border:none}
      edo:            { name: Estado, params: readonly=true size=40 style=border:none}
      mun:            { name: Municipio, params: readonly=true size=40 style=border:none}
      par:            { name: Parroquia, params: readonly=true size=40 style=border:none}
      sec:            { name: Sector, params: readonly=true size=40 style=border:none}
      codclacomp:
        name: Solicitud de Contratacion
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Clacomp_Ocreglic
          clase: Occlacomp
          ajax: 0
          parametros: getprincipal="getCodclacomp" getsecundario="getDesclacomp" campoprincipal="codclacomp" camposecundario="desclacomp" campobase = "id"
      fecreg:         { name: Fecha Registro, params: onChange=CalculaFecha(this.value)}
      dias:           { name: Dias para el Vencimiento, params: onChange=CalculaFecha(this.value)}
      fecven:         { name: Fecha Vencimiento, params: readonly=true style=border:none}
      ente:           { name: Ente Contratante, params: readonly=true size=60 style=border:none}
      ptipcom:        { name: .}
      ptipcon:        { name: .}
      pacto:          { name: .}
      tipcom:         { name: Compra}
      tipcon:         { name: Tipo Solicitud Bienes/Servicio}
      acto:           { name: Acto Motivado}      
      codpre:
        name: Proyecto
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Preasiini_Cpdeftit
          clase: Cpdeftit
          ajax: 0
          parametros: getprincipal="getCodpre" getsecundario="getNompre" campoprincipal="codpre" camposecundario="nompre" campobase = "id"
      codprio:
        name: Prioridad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lipriocon
          clase: Lipriocon
          ajax: 0
          parametros: getprincipal="getCodprio" getsecundario="getDesprio" campoprincipal="codprio" camposecundario="desprio" campobase = "id"
      despro:          { name: Breve Descripción, type: textarea_tag, params: size="65x5"}
      codmon:          { name: Moneda}
      valcam:
        name: Valor Cambio
        msj_error: El Cambio es necesario
        catalogo:
          catalogoweb: Tscammon_codmon
          clase: Tscammon
          ajax: 6
          parametros: getprincipal="getValcam" getsecundario="getFeccam" campoprincipal="valcam" camposecundario="feccam" campobase = "id"
          catalogoparams: /param1/'."'+$('liprebas_codmon').value+'".'
          ajaxparams: +'."'".'&codmon='."'+$('liprebas_codmon').value".'
      pcodmon:         { name: .}
      grid:            { name: .}
      monpre:          { name: Monto Solicitud Moneda Original, params: readonly=true style=border:none}
      monpreletras:    { name: Son,  params: readonly=true style=border:none size=80}
      monpreext:       { name: Monto Solicitud Moneda Extranjera, params: readonly=true style=border:none}
      monpreextletras: { name: Son,  params: readonly=true style=border:none size=80}
      docane1:
        name:  Documento Anexo 1
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 1***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane2:
        name:  Documento Anexo 2
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 2***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane3:
        name:  Documento Anexo 3
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 3***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      prepor:          { name: Preparado Por, params: size=80}
      cargopre:        { name: Cargo, params: size=80}
      lisicact_id:    { name: Declaratoria Modalidad, params: include_blank="Seleccione..." }
      detdecmod:       { name: Declaratoria Modalidad, type: textarea_tag, params: size="80x5"}
      aprpor:          { name: Analisado Por, params: size=80}
      cargoapr:        { name: Cargo, params: size=80}
      js:              { name: .}
      grid_rec:        { name: .}

    list:
      title: Presupuesto Base
      display: [=numpre, nompre, ejepre, coduniadm, desuniadm, coduniste, desuniste]
      filters: [numpre, nompro]
      fields:
        desuniadm:     { name: Descripción}
        desuniste:     { name: Descripción}
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page: 15
      sort: numpre


    edit:
      title: Presupuesto Base
      display:
        Datos Generales:     [ente, codempadm, nomcaradm, coduniadm, codempeje, nomcareje, coduniste, numpre, ejepre, _ptipcon, codclacomp, fecreg, dias, fecven, _ptipcom, _pacto, codpre, codprio, despro, _pcodmon, valcam ]
        Materiales Bienes/Servicios: [grid_rec, _grid, monpre, monpreletras, monpreext, monpreextletras]
        Otros Datos: [docane1, docane2, docane3, prepor, cargopre, lisicact_id, detdecmod, aprpor, cargoapr, _js]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~