opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   Liprebasdet
  anchogrid:               900
  ancho:                   850
  filas:                   1
  titulo:                  ' Artículos '
  htmltotalfilas:          ' '
1:       # Columna 2
  titulo:                  Artículo
  tipo:                    t
  nombrecampo:             codart
  esgrabable:              true
  catalogo:                [caregart, sf_admin_edit_form, {Codart: 1, Desart: 2, Unimed: 7 }, Caregart_Faproalt ]
  html:                    [size=15 ]
2:       # Columna 3
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desart
  esgrabable:              false
  html:                    [size=20 readonly=true ]
3:       # Columna 4
  titulo:                  Categoria Presupuestaria
  tipo:                    t
  nombrecampo:             codcat
  esgrabable:              true
  catalogo:                [Npcatpre, sf_admin_edit_form, {Codcat: 3, Nomcat: 4 }, Npcatpre_Almreq ]
  ajaxfila:                true
  html:                    [ size=15 ]
4:       # Columna 5
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             nomcat
  esgrabable:              false
  html:                    [ size=20 readonly=true ]
5:       # Columna 4
  titulo:                  Codigo Presupuestario
  tipo:                    t
  nombrecampo:             codpre
  esgrabable:              true
  html:                    [ readonly=true size=30 ]
6:       # Columna 4
  titulo:                  Disponibilidad
  tipo:                    m
  nombrecampo:             dispo
  esgrabable:              false
  html:                    [ readonly=true ]
7:       # Columna 5
  titulo:                  Unidad de Medida
  tipo:                    t
  nombrecampo:             unimed
  esgrabable:              true
  html:                    [ readonly=true ]
8:       # Columna 5
  titulo:                  Cantidad Solicitada
  tipo:                    m
  nombrecampo:             cansol
  esgrabable:              true
  ajaxfila:                true
  html:                    [ ]
9:       # Columna 5
  titulo:                  Cantidad Aprobada
  tipo:                    m
  nombrecampo:             canapr
  esgrabable:              true
  ajaxfila:                true
  html:                    [ readonly=true ]
10:       # Columna 5
  titulo:                  Precio Unitario Moneda Origen
  tipo:                    m
  nombrecampo:             costo
  esgrabable:              true
  ajaxfila:                true
  html:                    [ ]
11:       # Columna 5
  titulo:                  Precio Unitario Moneda Extranjera
  tipo:                    m
  nombrecampo:             costoe
  esgrabable:              true
  oculta:                  true
  ajaxfila:                true
  html:                    [ readonly=true ]
12:       # Columna 5
  titulo:                  Sub-Total Moneda Origen
  tipo:                    m
  nombrecampo:             subtot
  esgrabable:              true
  html:                    [ readonly=true ]
13:       # Columna 5
  titulo:                  Sub-Total Moneda Extranjera
  tipo:                    m
  nombrecampo:             subtote
  esgrabable:              true
  oculta:                  true
  html:                    [ readonly=true ]
14:       # Columna 5
  titulo:                  Total Recargos
  tipo:                    m
  nombrecampo:             monrec
  esgrabable:              true
  html:                    [ readonly=true ]
15:       # Columna 5
  titulo:                  Total Moneda Origen
  tipo:                    m
  nombrecampo:             montot
  esgrabable:              true
  #estotal:                 [true, liprebas_monpre ]
  html:                    [ readonly=true ]
16:       # Columna 5
  titulo:                  Total Moneda Extranjera
  tipo:                    m
  nombrecampo:             montote
  esgrabable:              true
  oculta:                  true
  #estotal:                 [true, liprebas_monpreext ]
  html:                    [ readonly=true ]
17:       # Columna 5
  titulo:                  Valor Cambio
  tipo:                    m
  nombrecampo:             valcam
  esgrabable:              true 
  html:                    [ readonly=true ]
18:       # Columna 5
  titulo:                  Recargos
  tipo:                    t
  nombrecampo:             recarg
  esgrabable:              false
  html:                    [  ]
19:       # Columna 5
  titulo:                  Cadena de Recargos
  tipo:                    t
  nombrecampo:             cadena
  esgrabable:              true
  oculta:                  true
  html:                    [  ]
20:       # Columna 2
  titulo:                  Finaciamiento
  tipo:                    t
  nombrecampo:             codfin
  esgrabable:              true
  catalogo:                [fortipfin, sf_admin_edit_form, {codfin: 20, Nomext: 21 }, Fortipfin_Pagemiord ]
  html:                    [size=15 ]
21:       # Columna 3
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             nomext
  esgrabable:              false
  html:                    [size=20 readonly=true ]