generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Nptipded
    theme:            default
    fields:
      codtip: { name: Código, params: maxlength=4,size=6}
      destip: { name: Descripción }
    list:
      title:          Tipo de Dedicación
      filters:        [codtip, destip ]
      display:        [=codtip, destip ]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
      sort:   codtip
    edit:
      title:          Edición de Tipo de Dedicación
      display:        [codtip, destip ]
      fields:
        codtip: 
          params:     maxlength=4,size=5 onBlur  = "$(this.id).value=$(this.id).value.pad(4,'0',0)"
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~