generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Fcvalinm
    theme:            cidesaGenerator
    fields:
      codzon:    { name: Zona, params: size=10 maxlength=3}
      deszon:    { name: Descripción, params: size=40 maxlength=50 }
      codtip:    { name: Código, params: size=10 maxlength=3}
      destip:    { name: . , params: size=40 maxlength=150 }
      valmtr:    { name: Valor del M2 (Bs.) , params: size=10 }
      valfis:    { name: Valor Fiscal M2, params: size=10 }
      alitip:    { name: Automatico, params: size=10 }
      anual:     { name: Solo aplicables a deudas del Año actual, params: size=10 }
      alitipt:   { name: Modo , params: size=10 }
      anualt:    { name: Limitar pagar Año Completo, params: size=10 }
      anovig:    { name: Año Vigencia, params: size=4 maxlength=4}
      porvalfis: { name: % Valor Fiscal, params: size=10 }
      grid:      { name: . }
    list:
      title:     Definición Inmuebles Urbanos  - Cuadro de Especificaciones para Cálculo de Impuestos
      display:   [=codzon, deszon]
      sort:      deszon
      filters:   [codzon, deszon]
      fields:
        deszon:
          params: size=10
      max_per_page: 10
      object_actions:
        _edit:        ~
        _delete:      ~
      sort:  codzon
    edit:
      title:          Edición de Inmuebles Urbanos  - Cuadro de Especificaciones para Cálculo de Impuestos
      display:
        "Datos Generales":   [ codzon, deszon, _anovig, _valmtr, _porvalfis, valfis ]
        "Asociación de Recaudos":   [ _grid ]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~