generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Fcsollic
    theme:            default
    fields:
      numsol:      { name: Número}
      fecsol:      { name: Fecha, params: date_format='dd/MM/yyyy'} 
      numlic:      { name: Número de Licencia}
      feclic:      { name: Fecha, params: date_format='dd/MM/yyyy'}  
      rifcon:      { name: C.I. / RIF. }
      nomcon:      { name: Nombre }
      dircon:      { name: Dirección }
      nacconrep:   { name: Nacionalidad}
      rifrep:      { name: C.I. / RIF. Representante}
      nomconrep:   { name: Nombre}
      dirconrep:   { name: Dirección}
      tomo:        { name: Tomo}
      folio:       { name: Folio}
      numero:      { name: Numero}
      implic:      { name: Impuesto a Pagar}
      fecapr:      { name: Aprobación}
      fecha:       { name: Renovacion}
      fecven:      { name: Vencimiento}
    list:
      title:          Licencia - Patente de Industria y Comercio
      display:        [=numsol, numlic, fecsol]
      filters:        [numsol]
      object_actions:
        _edit:        ~
        _delete:      ~              
      max_per_page:   10    
    edit:
      title:          Licencia - Patente de Industria y Comercio
      display:        [numsol, fecsol, rifcon, numlic, feclic, nomcon, dircon, nacconrep, rifrep, nomconrep, dirconrep, tomo, folio, numero, implic, fecapr, fecha, fecven]          

     