generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Fadefpro
    theme:            cidesaGenerator
    fields:
      codprod: { name: CÃ³digo, params : size=10 maxlength=8  onFocus=readonly(this.id) onBlur="this.value=this.value.pad(8, '0',0);"}
      desprod: { name: DescripciÃ³n, params : size=80 maxlength=250 }
    list:
      title:          Productos
      filters:        [codprod, desprod]
      display:        [=codprod, desprod]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
      sort:      codprod
    edit:
      title:          EdiciÃ³n de Producto
      display:
        "Datos":   [codprod, desprod]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~