generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Atprovee
    theme:            cidesaGenerator

    fields:
      nompro:      { name: Razón Social }
      rifpro:         { name: Rif }
      nitpro:      { name: Nit }
      dirpro:         { name: Dirección }
      telpro:      { name: Telefono }      

    list:
      title:          Registro de Proveedores
      display:        [=nompro, rifpro,dirpro]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [nompro, rifpro]
      max_per_page:   10
    edit:
      title:          Edición de Proveedores
      display:        [nompro, rifpro, nitpro, dirpro, telpro]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
