opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   ocemppar
  ancho:				   750
  anchogrid:               700
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código Empresa
  tipo:                    t
  nombrecampo:             codpro
  esgrabable:			   true
  html:                    [size='20']
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             nompro
  html:                    [readonly=true size=25]
3:       # Columna 3
  titulo:                  Fecha
  tipo:                    f
  nombrecampo:             fecins
  esgrabable:			   true
  html:                    [ ]
4:       # Columna 4
  titulo:                  Precalifica
  tipo:                    k
  nombrecampo:             precal
  esgrabable:			   true
  html:                    [ ]
5:       # Columna 5
  titulo:                  Monto Total
  tipo:                    m
  nombrecampo:             montot
  esgrabable:			   true
  html:                    [size=10]
6:       # Columna 6
  titulo:                  Observaciones
  tipo:                    t
  nombrecampo:             observaciones
  html:                    [size="35" maxlength=1000]
  esgrabable:              true