opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   opdetord
  anchogrid:               700
  ancho:                   500
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  CÃ³digo Presupuestario
  tipo:                    t
  nombrecampo:             codpre
  esgrabable:              true
  html:                    [size="20" readonly=true]
2:       # Columna 2
  titulo:                  Monto
  tipo:                    m
  esgrabable:              true
  nombrecampo:             moncau
  esnumerico:              true
  html:                    [size="10" readonly=true]