generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Npincapa
    theme:            cidesaGenerator
    fields:
      codinc:  { name: C贸digo }
      desinc:  { name: Descripci贸n }
      obsinc:  { name: Observaci贸n }

    list:
      title:          Incapacidades
      filters:        [codinc, desinc]
      display:        [=codinc, desinc]
      max_per_page:	  5
      sort:           codinc
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
    edit:
      title:          Edici贸n de Incapacidad
      display:        [_codinc, desinc, obsinc]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~