generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Dfatendocdet
    theme:            default
    fields:
      id_dfatendoc:   { name : Código Documento }
      coddoc:         { name : Código Documento } # Campo Foráneo
      id_usuario:     { name : Usuario }
      nomuse:         { name : Usuario }          # Campo Foráneo
      fecrec:         { name : Fecha Recepción }
      fecate:         { name : Fecha Atención }
      id_acunidad_ori:{ name : Unidad Origen }
      nomunio:        { name : Unidad Origen }    # Campo Foráneo
      id_acunidad_des:{ name : Unidad Destino }
      nomunid:        { name : Unidad Destino }   # Campo Foráneo
      id_dfrutadoc:   { name : Puesto en la Ruta }
      desate:         { name : Descripción de Atención }
      dias:           { name : Dias Consumidos }
      diadoc:         { name : Dias Planificados }
      diaent:         { name : Dias de Entrega }
      fecent:         { name : Fecha Aprox. Entrega }
      id_dfmedtra:    { name : Medio de Transporte }
    list:
      title:          Detalle Documento
      display:        [coddoc, nomuse, desate, fecrec, fecate, dias, diadoc, _fecent, nomunio, nomunid ]
      #filters:       [coddoc ]
      max_per_page:    10
    edit:
      title:          Detalle Documentos
      display:        [id_dfatendoc, nomuse, fecrec, horrec, fecate, horate, id_acunidad_ori, id_acunidad_des, diaent, id_dfmedtra ]
      actions:
        _list:        ~
        _save:        ~