generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Lirecomen
    theme:            cidesaGenerator
    fields:
      ente:           { name: Ente Contratante, params: readonly=true size=60 style=border:none}
      codempadm:
        name: Para
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 2
          parametros: getprincipal="getCodempadm" getsecundario="getNomempadm" campoprincipal="codempadm" camposecundario="nomempadm" campobase = "id"
      nomcaradm:      { name: Cargo, params: style=border:none}
      coduniadm:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 3
          parametros: getprincipal="getCoduniadm" getsecundario="getDesuniadm" campoprincipal="coduniadm" camposecundario="desuniadm" campobase = "id"
      codempeje:
        name: De
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 4
          parametros: getprincipal="getCodempeje" getsecundario="getNomempeje" campoprincipal="codempeje" camposecundario="nomempeje" campobase = "id"
      nomcareje:      { name: Cargo, params: style=border:none}
      coduniste:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 5
          parametros: getprincipal="getCoduniste" getsecundario="getDesuniste" campoprincipal="coduniste" camposecundario="desuniste" campobase = "id"
      numrecofe:      { name: Número Analisis Oferta, params: size=10 maxlength=8 onBlur=Correl(this.id) }
      numexp:
        name: No Expedientes
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Liplieesp_numexp
          clase: Liplieesp
          ajax: 1
          parametros: getprincipal="getNumexp" getsecundario="getDesnumexp" campoprincipal="numexp" camposecundario="desnumexp" campobase = "id"
          divupdate:  divgrid
      numplie:        { name: Número de Pliego }
      ejepre:         { name: Ejercicio Prespuestario Año, params: style="border:none"}
      desclacomp:     { name: Solicitud de Compra, params: style="border:none" size=80}
      destiplic:      { name: Modalidad de Contratación, params: style="border:none" size=80}
      tipcom:         { name: Compra, params: style="border:none" size=80}
      tipcon:         { name: Bienes/servicios, params: style="border:none" size=80}
      fecreg:         { name: Fecha Registro, params: onChange=CalculaFecha(this.value)}
      dias:           { name: Dias para el Vencimiento, params: onChange=CalculaFecha(this.value)}
      fecven:         { name: Fecha Vencimiento, params: readonly=true style=border:none}
      grid:           { name: .}
      recomen:        { name: Recomendación, type: textarea_tag, params: size="80x5" }
      docane1:
        name:  Documento Anexo 1
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 1***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane2:
        name:  Documento Anexo 2
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 2***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane3:
        name:  Documento Anexo 3
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 3***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      prepor:         { name: Preparado Por, params: size=80 }
      cargopre:      { name: Cargo, params: size=80 }
      lisicact_id:    { name: Declaratoria Modalidad, params: include_blank="Seleccione..." }
      detdecmod:      { name: Detalle Declaratoria Modalidad, type: textarea_tag, params: size="80x10" }
      anapor:         { name: Preparado Por, params: size=80 }
      cargoana:      { name: Cargo, params: size=80 }
      js:             {name: .}
      

    list:
      title:           Recomendación
      display:         [=numrecofe, numplie, numexp, desuniadm, desuniste, fecreg ]
      filters:         [numrecofe, numplie, numexp, coduniadm, coduniste, fecreg]
      fields:
        desuniadm:     { name: Para}
        desuniste:     { name: De}
      object_actions:
        _edit:          ~
        _delete:        ~
      max_per_page:    10
      sort:            numrecofe

    edit:
      title:           Recomendación
      display:
        Datos Generales:    [ente, codempadm, nomcaradm, coduniadm, codempeje, nomcareje, coduniste, numrecofe, numexp, numplie, ejepre, destiplic, desclacomp, tipcom, tipcon, fecreg, dias, fecven]
        Datos de las Ofertas:   [_grid, recomen]
        Otros:  [docane1, docane2, docane3]
        Delcaratoria: [prepor, cargopre, lisicact_id, detdecmod, anapor, cargoana, _js]
      fields:        
        numplie:      {params: readonly=true style=border:none}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~