generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Nptippre
    theme:            default
    fields:
      codtippre: { name: Codigo Tipo de Prestamo, params: readonly=true }
      destippre: {name: Descripcion, params: readonly=true }
      codcon: { name: Codigo del Concepto}
      nomcon: { name: Descripcion del Concepto}
      grid:   {name: ''}
    list:
      title:          Movimientos de Prestamos
      display:        [=codtippre, destippre, codcon, nomcon]
      filters:        [codtippre, codcon]
      object_actions:
        _edit:        ~
      actions:
        _create:        none
      max_per_page:   10
    edit:
      title:          Edici√≥n de Movimientos de Prestamos
      display:
        "Tipo de Prestamos":  [_codtippre, _codcon]
        "Empleados":  [_grid]
      actions:
        _list:          ~
        _save:          ~
        _delete:        none