generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Limemoran
    theme:            cidesaGenerator
    fields:
      numemo:         { name: Número Memorando, params: size=10 maxlength=8 onBlur=Correl(this.id) }
      numpre:
        name: Presupuesto Base
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Liprebas_numpre
          clase: Liprebas
          ajax: 1
          parametros: getprincipal="getNumpre" getsecundario="getDesnumpre" campoprincipal="numpre" camposecundario="desnumpre" campobase = "id"
      ejepre:         { name: Ejercicio Prespuestario Año, params: style="border:none"}
      codempadm:
        name: Para
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 2
          parametros: getprincipal="getCodempadm" getsecundario="getNomempadm" campoprincipal="codempadm" camposecundario="nomempadm" campobase = "id"
      nomcaradm:      { name: Cargo, params: style=border:none}
      coduniadm:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 3
          parametros: getprincipal="getCoduniadm" getsecundario="getDesuniadm" campoprincipal="coduniadm" camposecundario="desuniadm" campobase = "id"
      codempeje:
        name: De
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 4
          parametros: getprincipal="getCodempeje" getsecundario="getNomempeje" campoprincipal="codempeje" camposecundario="nomempeje" campobase = "id"
      nomcareje:      { name: Cargo, params: style=border:none}
      coduniste:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 5
          parametros: getprincipal="getCoduniste" getsecundario="getDesuniste" campoprincipal="coduniste" camposecundario="desuniste" campobase = "id"
      dirunieje:      { name: Dirección, params: readonly=true size=80 style=border:none}
      pai:            { name: Pais, params: readonly=true size=40 style=border:none}
      edo:            { name: Estado, params: readonly=true size=40 style=border:none}
      mun:            { name: Municipio, params: readonly=true size=40 style=border:none}
      par:            { name: Parroquia, params: readonly=true size=40 style=border:none}
      sec:            { name: Sector, params: readonly=true size=40 style=border:none}
      desclacomp:     { name: Solicitud de Contratación, params: size=80 style=border:none}
      fecreg:         { name: Fecha Registro, params: size=10 style=border:none}
      dias:           { name: Dias para el Vencimiento, params: size=5 style=border:none}
      fecven:         { name: Fecha Vencimiento, params: size=10 style=border:none}
      ente:           { name: Ente Contratante, params: size=80 style=border:none}
      tipcon:         { name: Tipo Solicitud Bien/Servicio, params: size=80 style=border:none}
      tipcom:         { name: Compra, params: size=80 style=border:none}
      acto:           { name: Acto Motivado, params: size=80 style=border:none}
      nomext:         { name: Financiamiento, params: size=80 style=border:none}
      nompre:         { name: Proyecto, params: size=80 style=border:none}
      desprio:        { name: Prioridad, params: size=80 style=border:none}
      despro:         { name: Breve Descripción, type: textarea_tag, params: size="80x5" }
      monpre:         { name: Monto Moneda Original, params: size=80 style=border:none}
      monpreext:      { name: Monto Moneda Extranjera, params: size=80 style=border:none}
      docane1:
        name:  Documento Anexo 1
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 1***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane2:
        name:  Documento Anexo 2
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 2***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane3:
        name:  Documento Anexo 3
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 3***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      prepor:         { name: Preparado Por, params: size=80 }
      preporcar:      { name: Cargo, params: size=80 }
      lisicact_id:    { name: Declaratoria Modalidad, params: include_blank="Seleccione..." }
      detdecmod:      { name: Detalle Declaratoria Modalidad, type: textarea_tag, params: size="80x10" }
      anapor:         { name: Preparado Por, params: size=80 }
      anaporcar:      { name: Cargo, params: size=80 }
      js:             {name: .}

    list:
      title:             Memorando Solicitud de Aprobación Egreso
      display:           [=numemo, despro, ejepre, desuniadm, desuniste]
      filters:           [numemo, despro]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:      15
      sort:              numemo

    edit:
      title:             Memorando Solicitud de Aprobación Egreso
      display:
        Datos Memorando:      [ente, codempadm, nomcaradm, coduniadm, codempeje, nomcareje, coduniste, numemo, numpre, ejepre, tipcon, desclacomp, fecreg, dias, fecven, tipcom, acto, nomext, nompre, desprio, despro, monpre, monpreext]
        Carga de Documentos:  [docane1, docane2, docane3]
        Detalle:              [prepor, preporcar, lisicact_id, detdecmod, anapor, anaporcar, _js]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~