default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo de Viaticos
    robots:       index, follow
    description:  Módulo Viaticos
    keywords:     Módulo, Viaticos
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, observe, ajax, dFilter]

  has_layout:     on
  layout:         layout
