propel:
  _attributes: { noXsd: false, defaultIdMethod: native, package: lib.model.ciudadanos }

  attipayu:                        # Tipos de Ayudas
    codayu:
      type: VARCHAR
      size: 8
      required: true
    desayu:
      type: VARCHAR
      size: 50
      required: true
    codpre:
      type: VARCHAR
      size: 100
    id:
  atrecaud:                        # Recaudos
    codrec:
      type: VARCHAR
      size: 8
      required: true
    desrec:
      type: VARCHAR
      size: 50
      required: true
    requerido:
      type: VARCHAR
      size: 1
      required: true
    id:
  atrecayu:                        # Asignar Recaudos a Ayudas
    attipayu_id:
    atrecaud_id:
    id:
  atestados:
    desest:
      type: VARCHAR
      size: 30
      required: true
    id:
  atmunicipios:
    atestados_id:
    desmun:
      type: VARCHAR
      size: 30
      required: true
    id:
  atparroquias:
    atmunicipios_id:
    despar:
      type: VARCHAR
      size: 30
      required: true
    id:
  atciudadano:                         # Ciudadano
    cedciu:
      type: VARCHAR
      size: 12
      required: true
    nomciu:
      type: VARCHAR
      size: 50
      required: true
    apeciu:
      type: VARCHAR
      size: 50
      required: true
    nacciu:
      type: VARCHAR
      size: 50
      required: true
    pais:
      type: VARCHAR
      size: 50
    conext:
      type: VARCHAR
      size: 100
    lugnac:
      type: VARCHAR
      size: 100
    tipo:      # Cooperativa, Particular, Consejo Comunal, Empresa, Organismo del Estado
      type: VARCHAR
      size: 1
      required: true
    sexo:
      type: VARCHAR
      size: 1
    fecnac:
      type: DATE
    dirnac:
      type: VARCHAR
      size: 100
    estciv:
      type: VARCHAR
      size: 1
    telhab:
      type: VARCHAR
      size: 25
    teladihab:
      type: VARCHAR
      size: 25
    prociu:
      type: VARCHAR
      size: 30
    atestados_id:
    atmunicipios_id:
    atparroquias_id:
    ciudad:
      type: VARCHAR
      size: 50
    caserio:
      type: VARCHAR
      size: 50
    dirhab:
      type: VARCHAR
      size: 100
    dirtra:
      type: VARCHAR
      size: 100
    concomciu:
      type: VARCHAR
      size: 100
    carconcomciu:
      type: VARCHAR
      size: 50
    nota:
      type: VARCHAR
      size: 100
    grains:
      type: VARCHAR
      size: 100
    traciu:
      type: BOOLEAN
    nomemp:
      type: VARCHAR
      size: 100
    diremp:
      type: VARCHAR
      size: 100
    telemp:
      type: VARCHAR
      size: 25
    attiping_id:
    moning:
      type: NUMERIC
      size: 14
      scale: 2
    atinsrefier_id:
    ayusolant:
      type: VARCHAR
      size: 1
    insayuant:
      type: VARCHAR
      size: 50
    segpri:
      type: BOOLEAN
    attipproviv_id:
    attipviv_id:
    id:
  attiping:                 # Tipo de Ingreso
    tiping:
      type: VARCHAR
      size: 50
    id:
  attipviv:                 # Tipo de Vivienda
    tipviv:
      type: VARCHAR
      size: 50
    id:
  attipproviv:                 # Tipo de Propiedad de la Vivienda
    tipproviv:
      type: VARCHAR
      size: 50
    id:
  atestsoceco:             # Estudio Socio economico
    atayudas_id:
    atciudadano_id:
    attipviv_id:
    attipproviv_id:          # Tipo de Propiedad de la Vivienda
    carvivsal:  # Caract. Viv. Sala
      type: BOOLEAN
    carvivcom:  # Caract. Viv. Comedor
      type: BOOLEAN
    carvivhab:  # Caract. Viv. Habitaciones
      type: BOOLEAN
    carvivcoc:  # Caract. Viv. Cocina
      type: BOOLEAN
    carvivban:  # Caract. Viv. Banos
      type: BOOLEAN
    carvivpat:  # Caract. Viv. Patio
      type: BOOLEAN
    carvivarever:  # Caract. Viv. Areas Verdes
      type: BOOLEAN
    carvivpis:  # Caract. Viv. Piso
      type: BOOLEAN
    carvivpar:  # Caract. Viv. Paredes
      type: BOOLEAN
    carvivtec:  # Caract. Viv. Techo
      type: BOOLEAN
    anasoceco:  # Analisis SocioEconomico
      type: VARCHAR
      size: 1000
    anafam:  # Analisis Familiar
      type: VARCHAR
      size: 1000
    otros:  # Otras informaciones
      type: VARCHAR
      size: 1000
    motvis:				# motivo Visita
      type: VARCHAR
      size: 5000
    ###  Nuevo Campos Oro Negro ###
    parfri:				# Pared frisada
      type: BOOLEAN
    parintext:			# Pare interna (I) o externa (E) frisada
      type: VARCHAR
      size: 1
    obspar:
      type: VARCHAR
      size: 1000    
    parsinfri:				# Pared sin frisada
      type: BOOLEAN
    parsinintext:			# Pare interna (I) o externa (E) sin frisar
      type: VARCHAR
      size: 1
    parmad:					# Paredes de Madera
      type: BOOLEAN
    parzin:					# Paredes de Zinc
      type: BOOLEAN
    parmatdes:					# Paredes de Materiales de Desechos
      type: BOOLEAN
    suecemrus:					# Suelo de cemento rustico
      type: BOOLEAN
    suecempul:					# Suelo de cemento pulido
      type: BOOLEAN
    suetie:					# Suelo de Tierra
      type: BOOLEAN
    suecer:					# Suelo de Cerámica
      type: BOOLEAN
    suegra:					# Suelo de granito
      type: BOOLEAN
    suepar:					# Suelo de parquet
      type: BOOLEAN
    suelin:					# Suelo de Linoleo
      type: BOOLEAN
    obssue:					# Observaciones del suelo
      type: VARCHAR
      size: 1000    
    teczin:					# Techo de Zinc
      type: BOOLEAN			
    tecmatdes:					# Techo de materiales de desechos
      type: BOOLEAN			
    tecace:					# Techo de Acerolí
      type: BOOLEAN			
    teccar:					# Techo de Cartón
      type: BOOLEAN			
    tectej:					# Techo de tejas
      type: BOOLEAN			
    tecado:					# Techo de Adobe
      type: BOOLEAN			
    obstec:					# Observaciones del Techo
      type: VARCHAR
      size: 1000    
    vivnroamb:				# Vivienda - Nro de Ambientes
      type: INTEGER
    vivnrohab:				# Vivienda - Nro de Habitaciones
      type: INTEGER
    vivnroban:				# Vivienda - Nro de Habitaciones
      type: INTEGER
    bandenviv:				# Baños dentro de la vivienda
      type: INTEGER
    banfueviv:				# Baños fuera de la vivienda
      type: INTEGER
    vivlet:					# Vivienda - Letrina
      type: BOOLEAN			
    vivwat:					# Vivienda - Walter Clock
      type: BOOLEAN			
    vivotr:					# Vivienda - Otro
      type: BOOLEAN			
    vivduc:					# Vivienda - Ducha
      type: BOOLEAN			
    vivlav:					# Vivienda - Lavamanos
      type: BOOLEAN			
    vivpar:					# Vivienda - Paredes
      type: VARCHAR
      size: 100
    vivpis:					# Vivienda - Pisos
      type: VARCHAR
      size: 100
    vivsal:					# Vivienda - sala
      type: BOOLEAN
    vivcom:					# Vivienda - comedor
      type: BOOLEAN
    vivsalcom:					# Vivienda - Sala-Comedor
      type: BOOLEAN
    vivcocdenviv:					# Vivienda - Cocina dentro de la vivienda
      type: BOOLEAN
    vivcocfueviv:					# Vivienda - Cocina fuera de la vivienda
      type: BOOLEAN
    viaaccvivasf:					# Vias de acceso a la vivienda - Asfaltada
      type: BOOLEAN
    viaaccvivtie:					# Vias de acceso a la vivienda - Tierra
      type: BOOLEAN
    viaaccvivesc:					# Vias de acceso a la vivienda - Escaleras
      type: BOOLEAN
    tramet:					# transporte - metro
      type: BOOLEAN
    trafer:					# transporte - ferrocarril
      type: BOOLEAN
    tracam:					# transporte - camioneta
      type: BOOLEAN
    trajee:					# transporte - Jeep
      type: BOOLEAN
    tralan:					# transporte - Lancha
      type: BOOLEAN
    trabar:					# transporte - barco
      type: BOOLEAN
    tracami:					# transporte - caminata
      type: BOOLEAN
    agufredia:					# Agua Frecuencia - Diaria
      type: BOOLEAN
    agufreint:					# Agua Frecuencia - Interdiaria
      type: BOOLEAN
    agufresem:					# Agua Frecuencia - Semanal
      type: BOOLEAN
    agufre15d:					# Agua Frecuencia - Cada 15 dias
      type: BOOLEAN
    aguportub:					# Agua por tuberias
      type: BOOLEAN
    agupordep:					# Agua por depositos
      type: BOOLEAN
    aguserdes:					# Agua Servida desague
      type: BOOLEAN
    aguserpoz:					# Agua Servida pozo séptico
      type: BOOLEAN
    aseurbdia:					# Aseo Urbano Diario
      type: BOOLEAN
    aseurbint:					# Aseo Urbano Interdiario
      type: BOOLEAN
    aseurbsem:					# Aseo Urbano Semanal
      type: BOOLEAN
    aseurb15d:					# Aseo Urbano cada 15dias
      type: BOOLEAN
    elepag:					# Electricidad Pagada
      type: BOOLEAN
    elepar:					# Electricidad Parasitaza
      type: BOOLEAN
    gasbom:					# gas por bombonas
      type: BOOLEAN
    gasdir:					# gas directo
      type: BOOLEAN
    toting:					# Socio Economica - Total ingreso
      type: NUMERIC
      size: 14
      scale: 2
    egrviv:					# Socio Economica - Egreso en la vivienda
      type: NUMERIC
      size: 14
      scale: 2
    egrtra:					# Socio Economica - Egreso en transporte
      type: NUMERIC
      size: 14
      scale: 2
    egredu:					# Socio Economica - Egreso en educacion
      type: NUMERIC
      size: 14
      scale: 2
    egrali:					# Socio Economica - Egreso en alimentacion
      type: NUMERIC
      size: 14
      scale: 2
    egrtel:					# Socio Economica - Egreso en telefono
      type: NUMERIC
      size: 14
      scale: 2
    egrluzase:					# Socio Economica - Egreso en luz y aseo
      type: NUMERIC
      size: 14
      scale: 2
    egragu:					# Socio Economica - Egreso en agua
      type: NUMERIC
      size: 14
      scale: 2
    egrgas:					# Socio Economica - Egreso en gas
      type: NUMERIC
      size: 14
      scale: 2
    egrotr:					# Socio Economica - Egreso otros
      type: NUMERIC
      size: 14
      scale: 2
    totegr:					# Socio Economica - Total Egreso
      type: NUMERIC
      size: 14
      scale: 2
    diasoc:					# Diagnostico Social
      type: VARCHAR
      size: 5000
    trasoc:					# Tratamiento Social
      type: VARCHAR
      size: 5000
    recome:					# recomendaciones
      type: VARCHAR
      size: 5000
    diasoc:					# Diagnostico Social
      type: VARCHAR
      size: 5000
    observ:					# Observaciones
      type: VARCHAR
      size: 5000
    id:
  attrasoc:                     # Trabajadora Social
    cedtra:
      type: VARCHAR
      size: 12
    nomtra:
      type: VARCHAR
      size: 50
    apetra:
      type: VARCHAR
      size: 50
    nrocol:             # Numero de colegio
      type: VARCHAR
      size: 50
    id:
  atgrufam:                      # Grupo Familiar
    atciudadano_id:
    cedfam:
      type: VARCHAR
      size: 12
    nomfam:
      type: VARCHAR
      size: 50
      required: true
    apefam:
      type: VARCHAR
      size: 50
      required: true
    edad:
      type: INTEGER
      required: true
    parfam: # Parentesco del familiar
      type: VARCHAR
      size: 50
      required: true
    ocufam: # Ocupacion del familiar
      type: VARCHAR
      size: 50
    moning:
      type: NUMERIC
      size: 14
      scale: 2
    id:
  atayudas:                              # Ayudas a ciudadanos
    nroexp:
      type: VARCHAR
      size: 50
    refdoc:
      type: INTEGER
      foreignTable: caordcom
      foreignReference: id
    parentesco:
      type: INTEGER    
    priayu:
      type: INTEGER
      required: true
    atpriayu_id:
    atsolici:
      type: INTEGER
      required: true
      foreignTable: atciudadano
      foreignReference: id
    atbenefi:
      type: INTEGER
      required: true
      foreignTable: atciudadano
      foreignReference: id
    attipayu_id:
    atrubros_id:
    atestayu_id:
    attrasoc_id:
    atprovee_id:
    proayu:
      type: VARCHAR
      size: 100
    nroofi:
      type: VARCHAR
      size: 50
    desayu:
      type: VARCHAR
      size: 50
    motayu:
      type: VARCHAR
      size: 50
    created_at:
    updated_at:
    usucre:
      type: VARCHAR
      size: 50
    usumod:
      type: VARCHAR
      size: 50
    codpre:
      type: VARCHAR
      size: 50
    detayu:
      type: VARCHAR
      size: 1000
    monayu:
      type: NUMERIC
      size: 14
      scale: 2
    monapr:
      type: NUMERIC
      size: 14
      scale: 2
    atmedico_id:
    respat:
      type: VARCHAR
      size: 5000
    infmed:
      type: VARCHAR
      size: 5000
    obsmed:
      type: VARCHAR
      size: 5000
    fecdiasoc:
      type: DATE
    usudiasoc:
      type: VARCHAR
      size: 100
    resdiasoc:
      type: VARCHAR
      size: 5000
    fecvisdoc:
      type: DATE
    usuvisdoc:
      type: VARCHAR
      size: 100
    resvisdoc:
      type: VARCHAR
      size: 5000
    fecsol:
      type: DATE
    id:
  atdetrecayu:                           # Detalle de recaudos entregados para llevar a cabo la ayuda
    atayudas_id:
    atrecaud_id:
    id:
  atestayu:                     # Estados de Ayudas
    desest:
      type: VARCHAR
      size: 50
      required: true
    comest:         # Comportamiento del Estado
      type: VARCHAR
      size: 1
      required: true
    id:
  atgrudon:                     # Grupos de Articulos a Donar
    codgru:
      type: VARCHAR
      size: 10
      required: true
    desgru:
      type: VARCHAR
      size: 100
      required: true
    id:
  atdonaciones:                 # Articulos a Donar
    coddon:
      type: VARCHAR
      size: 50
      required: true
    desdon:
      type: VARCHAR
      size: 100
      required: true
    unidon:
      type: VARCHAR
      size: 50
      required: true
    id:
  atdetayu:                              # Detalle de la ayuda solicitada
    atayudas_id:
    atdonaciones_id:
    cantidad:
      type: INTEGER
    canapr:
      type: INTEGER
    aprobado:
      type: BOOLEAN
    precio:
      type: NUMERIC
      size: 14
      scale: 2
    unidad:
      type: VARCHAR
      size: 50
    id:
  atfacturas:
    atayudas_id:
    numfac:
      type: VARCHAR
      size: 50
      required: true
    basimp:
      type: NUMERIC
      size: 14
      scale: 2
    iva:
      type: NUMERIC
      size: 14
      scale: 2
    exentos:
      type: NUMERIC
      size: 14
      scale: 2
    total:
      type: NUMERIC
      size: 14
      scale: 2
    nrospd:
      type: VARCHAR
      size: 50
    id:
  atunidades:                           # Unidades
    coduni:
      type: VARCHAR
      size: 8
      required: true
    desuni:
      type: VARCHAR
      size: 30
      required: true
    diruni:
      type: VARCHAR
      size: 30
    telfuni:
      type: VARCHAR
      size: 30
    percon:    # Persona de contacto
      type: VARCHAR
      size: 30
    telpercon:
      type: VARCHAR
      size: 30
    mailpercon:
      type: VARCHAR
      size: 30
    horario:
      type: VARCHAR
      size: 30
    id:
  atreclamos:                                  # Reclamos
    atsolici:
      type: VARCHAR
      size: 50
      required: true
    desrec:
      type: VARCHAR
      size: 30
      required: true
    telefono:
      type: VARCHAR
      size: 60
    atunidades_id:
    persona:
      type: VARCHAR
      size: 30
    status:
      type: VARCHAR
      size: 1
    respuesta:
      type: VARCHAR
      size: 100
    fechaa:
      type: DATE
    fechar:
      type: DATE
    id:
  atdenuncias:                                # Denuncias
    atsolici:
      type: VARCHAR
      size: 30
      required: true
    desden:
      type: VARCHAR
      size: 30
      required: true
    telefono:
      type: VARCHAR
      size: 60
    atunidades_id:
    persona:
      type: VARCHAR
      size: 30
    status:
      type: VARCHAR
      size: 1
    respuesta:
      type: VARCHAR
      size: 100
    fechaa:
      type: DATE
    fechar:
      type: DATE
    id:
  ataudiencias:                               # Audiencias
    atciudadano_id:
    motaud:
      type: VARCHAR
      size: 30
      required: true
    atunidades_id:
    persona:
      type: VARCHAR
      size: 30
    status:
      type: VARCHAR
      size: 1
    fecha:
      type: DATE
    fechar:
      type: DATE
    fechaa:
      type: DATE
    lugar:
      type: VARCHAR
      size: 100
    observacion:
      type: VARCHAR
      size: 30
    id:
  atrubros:       #Rubros, subgrupo de tipos de ayudas
    attipayu_id:
    desrub:
      type: VARCHAR
      size: 100
      required: true
    id:
  atdefemp:
    #_attributes:
      #idMethod: native
    codemp:
      type: VARCHAR
      size: 15
      required: true
    nomemp:
      type: VARCHAR
      size: 100
      required: true
    diremp:
      type: VARCHAR
      size: 100
      required: true
    telemp:
      type: VARCHAR
      size: 30
      required: true
    faxemp:
      type: VARCHAR
      size: 15
    emaemp:
      type: VARCHAR
      size: 100
    percon:
      type: VARCHAR
      size: 150
    repleg:
      type: VARCHAR
      size: 150
    preasi:
      type: NUMERIC
      size: 14
      scale: 2
    monlimben:
      type: NUMERIC
      size: 14
      scale: 2
    id:
  atdetrecrub:                           # Detalle de recaudos por rubros
    atrubros_id:
    atrecaud_id:
    requerido:
      type: VARCHAR
      size: 1
      required: true
    id:
  atmedico:                         # Medico Tratante
    cedrifmed:
      type: VARCHAR
      size: 15
      required: true
    nombremed:
      type: VARCHAR
      size: 50
      required: true
    apellimed:
      type: VARCHAR
      size: 50
      required: true
    dirhabmed:
      type: VARCHAR
      size: 100
    dirtramed:
      type: VARCHAR
      size: 100
    telunomed:
      type: VARCHAR
      size: 25
    teldosmed:
      type: VARCHAR
      size: 25
    nrocolmed:
      type: VARCHAR
      size: 25    
    id:
  atinsrefier:
    desinsref:
      type: VARCHAR
      size: 50
      required: true
    id:
  atdocayu:
    atayudas_id:
    image:
      type: VARCHAR
      size: 100
      required: true
    desimg:
      type: VARCHAR
      size: 50
      required: true
    id:

  atprovee:
    nompro:
      type: VARCHAR
      size: 100
    rifpro:
      type: VARCHAR
      size: 100
    nitpro:
      type: VARCHAR
      size: 100
    dirpro:
      type: VARCHAR
      size: 1000    
    telpro:
      type: VARCHAR
      size: 100
    id:    
  atpresupuesto:
    atayudas_id:
    atprovee1:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto1:
      type: NUMERIC
      size: 14
      scale: 2
    atprovee2:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto2:
      type: NUMERIC
      size: 14
      scale: 2
    atprovee3:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto3:
      type: NUMERIC
      size: 14
      scale: 2
    atprovee4:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto4:
      type: NUMERIC
      size: 14
      scale: 2
    atprovee5:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto5:
      type: NUMERIC
      size: 14
      scale: 2
    atprovee6:
      type: INTEGER
      foreignTable: atprovee
      foreignReference: id
    monto6:
      type: NUMERIC
      size: 14
      scale: 2

  atpriayu:
    despriayu:
      type: VARCHAR
      size: 50
    id:
    
    
    