propel:
  _attributes: { noXsd: false, defaultIdMethod: native, package: lib.model }
  rharecur:
    codarecur:
      type: VARCHAR
      size: 4
      required: true
    desarecur:
      type: VARCHAR
      size: 250
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhasicur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    numcla:
      type: VARCHAR
      size: 3
      required: true
    codemp:
      type: VARCHAR
      size: 16
      required: true
    asicla:
      type: VARCHAR
      size: 1
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhclacur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    numcla:
      type: VARCHAR
      size: 3
      required: true
    feccla:
      type: DATE
    horini:
      type: VARCHAR
      size: 10
    horfin:
      type: VARCHAR
      size: 10
    numhor:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdateva:
    codevdo:
      type: VARCHAR
      size: 16
      required: true
    codevor:
      type: VARCHAR
      size: 16
    codsup:
      type: VARCHAR
      size: 16
    fecdes:
      type: DATE
    fechas:
      type: DATE
    fecela:
      type: DATE
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefcur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    descur:
      type: VARCHAR
      size: 250
    codtipcur:
      type: VARCHAR
      size: 4
      required: true
    codpro:
      type: VARCHAR
      size: 10
    fecini:
      type: DATE
    fecfin:
      type: DATE
    notapr:
      type: NUMERIC
      size: 14
      scale: 2
    durcur:
      type: NUMERIC
      size: 14
    codtit:
      type: VARCHAR
      size: 4
    turcur:
      type: VARCHAR
      size: 1
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefemp:
    codemp:
      type: VARCHAR
      size: 3
      required: true
    faxemp:
      type: VARCHAR
      size: 15
    porcom:
      type: NUMERIC
      size: 14
      scale: 2
    porobj:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefind:
    codind:
      type: VARCHAR
      size: 4
      required: true
    desind:
      type: VARCHAR
      size: 250
    tipind:
      type: VARCHAR
      size: 1
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefniv:
    codniv:
      type: VARCHAR
      size: 4
      required: true
    desniv:
      type: VARCHAR
      size: 250
    minpun:
      type: INTEGER
    maxpun:
      type: INTEGER  
    totpes:
      type: INTEGER  
    codran:
      type: VARCHAR
      size: 2
    tipcal:
      type: VARCHAR
      size: 1
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefobj:
    codobj:
      type: VARCHAR
      size: 4
      required: true
    desobj:
      type: VARCHAR
      size: 250
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhdefvalins:
    codvalins:
      type: VARCHAR
      size: 4
      required: true
    desvalins:
      type: VARCHAR
      size: 250
    obsvalins:
      type: VARCHAR
      size: 250
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhevaconcom:
    codevdo:
      type: VARCHAR
      size: 16
      required: true
    codniv:
      type: VARCHAR
      size: 4
      required: true
    codvalins:
      type: VARCHAR
      size: 4
      required: true
    pesval:
      type: NUMERIC
      size: 14
      scale: 2
    punval:
      type: NUMERIC
      size: 14
      scale: 2
    feceval:
      type: DATE  
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhevaempobj:
    codevdo:
      type: VARCHAR
      size: 16
      required: true
    codniv:
      type: VARCHAR
      size: 4
      required: true
    codobj:
      type: VARCHAR
      size: 4
      required: true
    plaobj:
      type: NUMERIC
      size: 14
      scale: 2
    alcobj:
      type: NUMERIC
      size: 14
      scale: 2
    pesobj:
      type: NUMERIC
      size: 14
      scale: 2
    punobj:
      type: NUMERIC
      size: 14
      scale: 2
    feceval:
      type: DATE        
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhindniv:
    codniv:
      type: VARCHAR
      size: 4
      required: true
    codind:
      type: VARCHAR
      size: 4
      required: true
    porind:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhinscur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    codemp:
      type: VARCHAR
      size: 16
      required: true
    codcar:
      type: VARCHAR
      size: 16
    fecins:
      type: DATE
    tipper:
      type: VARCHAR
      size: 1 
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhnotcur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    codemp:
      type: VARCHAR
      size: 16
      required: true
    notcur:
      type: NUMERIC
      size: 14
      scale: 2
    aprcur:
      type: VARCHAR
      size: 1
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhrelobjind:
    codevdo:
      type: VARCHAR
      size: 16
      required: true
    codniv:
      type: VARCHAR
      size: 4
      required: true
    codobj:
      type: VARCHAR
      size: 4
      required: true
    codind:
      type: VARCHAR
      size: 4
      required: true
    pesobj:
      type: NUMERIC
      size: 14
      scale: 2
    plaobj:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhtipcur:
    codtipcur:
      type: VARCHAR
      size: 4
      required: true
    destipcur:
      type: VARCHAR
      size: 250
    codarecur:
      type: VARCHAR
      size: 4
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhtitcur:
    codtit:
      type: VARCHAR
      size: 4
      required: true
    nomtit:
      type: VARCHAR
      size: 250
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  rhvalniv:
    codniv:
      type: VARCHAR
      size: 4
      required: true
    codvalins:
      type: VARCHAR
      size: 4
      required: true
    porvalins:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      autoIncrement: true
  rhprocur:
    codcur:
      type: VARCHAR
      size: 10
      required: true
    cedpro:
      type: VARCHAR
      size: 10
      required: true
    nompro:
      type: VARCHAR
      size: 100
    id:
      type: INTEGER
      required: true
      autoIncrement: true
  rhdefran:
    codran:
      type: VARCHAR
      size: 2
      required: true
    desran:
      type: VARCHAR
      size: 100
      required: true
    id:
      type: INTEGER
      required: true
      autoIncrement: true
  rhdefdetran:
    codran:
      type: VARCHAR
      size: 2
      required: true
    valran:
      type: NUMERIC
      size: 14
      scale: 2
      required: true
    desdet:
      type: VARCHAR
      size: 60
      required: true  
    valdes:
      type: NUMERIC
      size: 14
      scale: 2
      required: true
    valhas:
      type: NUMERIC
      size: 14
      scale: 2
      required: true     
    id:
      type: INTEGER
      required: true
      autoIncrement: true  