opciones:                  # Opciones generales
  name:                    b
  eliminar:                true
  tabla:                   fcdefrecdes
  ancho:                   600
  anchogrid:               600
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código
  tipo:                    t
  nombrecampo:             codrec
  esgrabable:			   true
  html:                    [size="10", readonly=true]
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desrec
  esgrabable:			   true
  html:                    [size="40", readonly=true]