generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Npdefespparpre
    theme:            cidesaGenerator
    fields:
      codnom:
        name:  Nómina
        msj_error: Debe Ingresar la Nomina
        catalogo:
          catalogoweb: Npnomina_nomdefespvar
          clase: Npnomina
          ajax: 0
          parametros: getprincipal="getCodnom" getsecundario="getNomnom" campoprincipal="codnom" camposecundario="nomnom" campobase = "id"                
        params:  maxlength=3  
      nomnom:            { name: Nombre Nómina}
      numdiames:         { name: Número de dias por Mes, params: maxlength=2 size=5}
      numdiamaxano:      { name: Número de dias Máximo por Año, params: maxlength=3 size=5}
      tipsalajunodep:    { name: Tipo de Salario Ajustes  no Depositados}
      ptipsalajunodep:   { name: .}
      tipsalbonfinanofra: { name: Tipo de Salario Bonificación de Fin de Año Fraccionado}
      ptipsalbonfinanofra: { name: Tipo de Salario Bonificación de Fin de Año Fraccionado}
      factorbonfinanofra: { name: Factor}
      ptipsalbonfinanofra: {name: .}
      tipsalbonvacfra: { name: Tipo de Salario Bono Vacacional Fraccionado}
      factorbonvacfra: { name: Factor}
      tipsalvacven: { name: Tipo de Salario Vacaciones Vencidas}
      factorvacven: { name: Factor}
      ptipsalbonvacfra: { name: .}
      descripclau:      { name:  Descripcion clausula }
      codpar:
        name:  Código Partida
        msj_error: Debe Ingresar La Partida
        catalogo:
          catalogoweb: Nppartidas_Almregart
          clase: Nppartidas
          ajax: 0
          parametros: getprincipal="getCodpar" getsecundario="getNompar" campoprincipal="codpar" camposecundario="nompar" campobase = "id"                
        params:  maxlength=32
      codret:
        name:  Tipo Retiro
        msj_error: Debe Ingresar Tipo de Retiro
        catalogo:
          catalogoweb: Nptipret_codret
          clase: Nptipret
          ajax: 0
          parametros: getprincipal="getCodret" getsecundario="getDesret" campoprincipal="codret" camposecundario="desret" campobase = "id"                
        params:  maxlength=2
      numdiaant:        { name: Numero de Dias}  
      poranoant:        { name: Por ano Antiguedad, type: checkbox_tag}
      tipsaldiaant:     { name: Tipo Salario Dias Antiguedad}
      aguicom:          { name: Aguinaldos Completos}
      apartirmes:       { name: Apartir de(meses)}
      ptipsaldiaant:    { name: .}
      paguinaldosmes:   { name: .}
      ptipsalvacven:    { name: .}
      
    list:
      title:          Lista de Parametros para Prestaciones
      display:        [=codnom, nomnom, numdiames, numdiamaxano]  
      filters:        [codnom]
      obj_actions:
        _edit:        ~
        _delete:      ~
      max_pers:       5
      sort:           codnom

    edit:
      title:          Edicion de Parametros para Prestaciones
      display:
        NONE:              [codnom]        
        Dias para Vacaciones:   [numdiames, numdiamaxano, _ptipsalajunodep]
        Bono Fin de Año Fraccionado: [_ptipsalbonfinanofra, factorbonfinanofra, _paguinaldosmes]
        Bono Vacacional Fraccionado: [_ptipsalbonvacfra, factorbonvacfra]
        Vacaciones Vencidas:         [_ptipsalvacven, factorvacven]
        Liquidacion de Prestaciones: [descripclau, codpar, codret, _ptipsaldiaant]
        
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~