generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Bnclafun
    theme:            default

    fields:
      codcla:      { name : Código }
      descla:      { name : Nombre }      
      stacla:      { name : p }


    list:
      title:          Definición de Clasificación Funcional
      display:        [=codcla, descla]
      filters:        [codcla, descla]
      object_actions:
        _edit:        ~
        _delete:      ~              
      max_per_page:   10    
    edit:
      title:          Edición Clasificación Funcional
      display:        [codcla, descla]    