opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   npdefrepcon
  anchogrid:               900
  ancho:                   850
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  N° Columna
  tipo:                    c
  nombrecampo:             numcol
  esgrabable:              true
  valida:                  true
  html:                    [ ]
2:       # Columna 2
  titulo:                  Nombre Columna
  tipo:                    t
  nombrecampo:             descol
  esgrabable:              true
  valida:                  true
  html:                    [ ]
3:       # Columna 5
  titulo:                  Concepto
  tipo:                    t
  nombrecampo:             codcon
  esgrabable:              true
  valida:                  true
  html:                    [ size=3 maxlength=3]
  catalogo:                [npdefcpt, sf_admin_edit_form, {Codcon: 3, Nomcon: 4}, Npdefcpt_codcon ]
4:       # Columna 6
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             nomcon
  esgrabable:              false
  html:                    [ readonly=true size=50]