generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      NpliquidacionDet
    theme:            cidesaGenerator

    fields:
      display: [nomemp, sue311296, sue180697, ultimosueldo, salarioint, fecing, feccor, fecegr, diaefe, mesefe, anoefe, diarn, mesrn, anorn, diara, mesra, anora, codret]
      codemp:
        name: Código Empleado
        msj_error: El numero del expediente es necesario
        catalogo:  
          catalogoweb: Nphispre_Presnomcalintpre
          clase: Nphojint 
          ajax: 0
          parametros: getprincipal="getCodemp" getsecundario="getNomemp" campoprincipal="codemp" camposecundario="nomemp" campobase = "id"           
          #catalogoparams:
          #ajaxparams:  
          #divupdate: divgridvaca     
          #id:
      sue311296:
        name: Ultimo Salario Devengado
      sue180697:
        name: Salario Promedio A la Fecha de Egreso
      ultimosueldo:
        name: Salario Normal A la Fecha de Egreso
      salarioint:
        name: Salario Integral A la Fecha de Egreso  
      salarios:
        name: .
      fecing:
        name: Ingreso
      feccor:
        name: Corte
      fecegr:
        name: Egreso
      fechas:
        name:.
      diaefe:
        name: Dia
      mesefe:
        name: Mes
      anoefe:
        name: Año
      diarn:
        name: Dia
      mesrn:
        name: Mes
      anorn:
        name: Año
      diara:
        name: Dia
      mesra:
        name: Mes
      anora:
        name: Año
      tiempo:
        name: .
      vacaciones:
        name: .
      asignaciones:
        name: .
      deducciones:
        name: .
      retiro:
        name: .
      codret:
        name: Tipo de Retiro    

    edit:
      title:  Liquidación de Prestaciones
      display:
        Datos del Empleados: [codemp, _retiro]
        Datos Generales de la Liquidacion de Prestaciones: [ _salarios, _fechas, _tiempo, _vacaciones]
        Asignaciones/Deducciones para la Liquidacion de Prestaciones: [_asignaciones, _deducciones]
      actions:
        _create:        ~
        _save:        ~
        _delete:      ~