opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   causualm
  anchogrid:               900
  ancho:                   800
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 2
  titulo:                  Marcar
  tipo:                    k
  nombrecampo:             check
  esgrabable:              true
  html:                    [ size=4  ]
2:       # Columna 3
  titulo:                  Almacén
  tipo:                    t
  nombrecampo:             codalm
  esgrabable:              true
  html:                    [ readonly=true size=8]
3:       # Columna 4
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             nomalm
  html:                    [ readonly=true size=100]
