default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo de Hacienda
    robots:       index, follow
    description:  Módulo de Hacienda
    keywords:     Módulo de Hacienda
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax ]


  has_layout:     on
  layout:         layout