default:
  http_metas:
    content-type: text/html

  metas:
    title:        Atención al Ciudadano
    robots:       index, follow
    description:  Atención al Ciudadano
    keywords:     Atención al Ciudadano
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, observe, ajax, tools ]

  has_layout:     on
  layout:         layout
