generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Ocregobr
    theme:            default
    fields:
      codobr: { name: Código}
      desobr: { name: Descripción}
      staobr: { name: Estatus}
      totalp: { name: Presupuestado}
      totala: { name: Asignado}
      totaldif: { name: Diferencia}
      totalc: { name: Contratado}
      totalcv: { name: Contratado Variado}
      pordif: { name: % Diferencia}
      porvarcon: { name: % Var. Contrato}
      moneje:   { name: Ejecutado}
      poreje:   { name: % Ejecutado}
      monporeje:   { name: Por Ejecutar}
      porxeje:   { name: % Por Ejecutar}
      totobreje:   { name: Total Obra Ejecutada}
      obrejefis:   { name: Obra Ejecutada Fisícamente}
    list:
      title:          Situación de la Obra
      filters:		  [codobr, desobr]
      display:        [=codobr, desobr]
      max_per_page:	  10
      object_actions:
        _edit:        ~
    edit:
      title:          Situación de la Obra
      display:        [codobr, desobr, totalp, totala, totaldif, totalc, totalcv, pordif, porvarcon, moneje, poreje, monporeje, porxeje, totobreje, obrejefis]
      actions:
        _list:        ~