generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Fatippag
    theme:            cidesaGenerator

    fields:
      destippag: { name: Nombre, validate: Vstring_1_30, msj_error: Debe insertar el nombre del tipo de pago }

    list:
      title: Tipos de Pago
      display: [=destippag]
      filters: [destippag]
      object_actions:
       _edit:        ~
       _delete:        ~
      max_per_page:	  10
      sort:    destippag

    edit:
      title: Definici√≥n de Tipo de Pago
      display:
        "NONE": [destippag]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
