generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Usuarios
    theme:            default
    fields:
      loguse:     { name : Usuario }
      nomuse:     { name : Nombre }
      pasuse:     { name : Contraseña }
      numuni:     { name : Unidad }
      nomuni:     { name : Nombre Unidad }
    list:
      title:          Administración de Usuarios
      display:        [=loguse, nomuse, nomuni ]
      filters:      [loguse, nomuse ]
      max_per_page:    5
      object_actions:
        _edit:        ~
        _delete:      ~
      actions:
        _list:       ~
    edit:
      title:          Edición de Usuarios
      display:        [loguse, nomuse, numuni ]
      actions:
        _list:        ~
        _save:        ~