generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Liptocuecon
    theme:            cidesaGenerator
    fields:
      ente:           { name: Ente Contratante, params: readonly=true size=60 style=border:none}
      codempadm:
        name: Para
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 2
          parametros: getprincipal="getCodempadm" getsecundario="getNomempadm" campoprincipal="codempadm" camposecundario="nomempadm" campobase = "id"
      nomcaradm:      { name: Cargo, params: style=border:none}
      coduniadm:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 3
          parametros: getprincipal="getCoduniadm" getsecundario="getDesuniadm" campoprincipal="coduniadm" camposecundario="desuniadm" campobase = "id"
      codempeje:
        name: De
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 4
          parametros: getprincipal="getCodempeje" getsecundario="getNomempeje" campoprincipal="codempeje" camposecundario="nomempeje" campobase = "id"
      nomcareje:      { name: Cargo, params: style=border:none}
      coduniste:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 5
          parametros: getprincipal="getCoduniste" getsecundario="getDesuniste" campoprincipal="coduniste" camposecundario="desuniste" campobase = "id"
      numptocuecon:   { name: Número Punto de Cuenta, params: size=10 maxlength=8 onBlur=Correl(this.id) }
      numrecofe:
        name: Recomendación Número
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lirecomen_numrecofe
          clase: Lirecomen
          ajax: 1
          parametros: getprincipal="getNumrecofe" getsecundario="getDesnumrecofe" campoprincipal="numrecofe" camposecundario="desnumrecofe" campobase = "id"
      numexp:         { name: Número Expediente }
      numplie:        { name: Número de Pliego }
      ejepre:         { name: Ejercicio Prespuestario Año, params: style="border:none"}
      desclacomp:     { name: Solicitud de Compra, params: style="border:none" size=80}
      destiplic:      { name: Modalidad de Contratación, params: style="border:none" size=80}
      tipcom:         { name: Compra, params: style="border:none" size=80}
      tipcon:         { name: Bienes/servicios, params: style="border:none" size=80}
      fecreg:         { name: Fecha Registro, params: onChange=CalculaFecha(this.value)}
      dias:           { name: Dias para el Vencimiento, params: onChange=CalculaFecha(this.value)}
      fecven:         { name: Fecha Vencimiento, params: readonly=true style=border:none}
      codpro:         { name: Codigo, params: style="border:none" size=80}
      nompro:         { name: Empresa, params: style="border:none" size=80}
      rifpro:         { name: Rif, params: style="border:none" size=80}
      nomrepleg:      { name: Representante Legal, params: style="border:none" size=80}
      direccion:      { name: Dirección, params: style="border:none" size=80}
      numofe:         { name: Número Oferta, params: style="border:none" size=80}
      fecofe:         { name: Fecha Oferta, params: style="border:none" size=80}
      monofe:         { name: MontoOferta, params: style="border:none" size=80}
      detrecomen:     { name: Detalle, type: textarea_tag, params:  size=80x5}
      resolu:         { name: Resolución}
      fecrel:         { name: Fecha}
      decret:         { name: Decreto/Punto de Cuenta}
      fecdec:         { name: Fecha}
      detdecret:      { name: Detalle, type: textarea_tag, params:  size=80x5}
      docane1:
        name:  Documento Anexo 1
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 1***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane2:
        name:  Documento Anexo 2
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 2***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane3:
        name:  Documento Anexo 3
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 3***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      prepor:         { name: Preparado Por, params: size=80 }
      cargopre:       { name: Cargo, params: size=80 }
      lisicact_id:    { name: Declaratoria Modalidad, params: include_blank="Seleccione..." }
      detdecmod:      { name: Detalle Declaratoria Modalidad, type: textarea_tag, params: size="80x10" }
      anapor:         { name: Preparado Por, params: size=80 }
      cargoana:       { name: Cargo, params: size=80 }
      js:             {name: .}

    list:
      title:           Punto de Cuenta AProbación Contratación
      display:         [=numptocuecon, numplie, numexp, desuniadm, desuniste, fecreg ]
      filters:         [numptocuecon, numplie, numexp, coduniadm, coduniste, fecreg]
      fields:
        desuniadm:     { name: Para}
        desuniste:     { name: De}
      object_actions:
        _edit:          ~
        _delete:        ~
      max_per_page:    10
      sort:            numptocuecon

    edit:
      title:           Punto de Cuenta AProbación Contratación
      display:
        Datos Generales:    [ente, codempadm, nomcaradm, coduniadm, codempeje, nomcareje, coduniste, numptocuecon, numrecofe, numexp, numplie, ejepre, destiplic, desclacomp, tipcom, tipcon, fecreg, dias, fecven]
        Recomendación:      [codpro, nompro, rifpro, nomrepleg, direccion, numofe, fecofe, monofe, detrecomen]
        Otros:  [resolu, fecrel, decret, fecdec, detdecret, docane1, docane2, docane3]
        Delcaratoria: [prepor, cargopre, lisicact_id, detdecmod, anapor, cargoana, _js]
      fields:
        numplie:      {params: readonly=true style=border:none}
        numexp:       {params: readonly=true style=border:none}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~