opciones:                  # Opciones generales
  eliminar:                true
  tabla:                   faartfacpro
  anchogrid:               900
  ancho:                   900
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Marque
  tipo:                    k
  nombrecampo:             check
  esgrabable:			   true
  html:                    [ ]
2:       # Columna 2
  titulo:                  Cod. Referencia
  tipo:                    t
  nombrecampo:             codref
  esgrabable:              true
  oculta:                  true
  html:                    [size="10"]
3:       # Columna 3
  titulo:                  Cod. Artículo
  tipo:                    t
  nombrecampo:             codart
  esgrabable:              true
  html:                    [size="20"]
4:       # Columna 4
  titulo:                  Descripción
  tipo:                    a
  nombrecampo:             desart
  esgrabable:              true
  html:                    [size="30x1"]
5:       # Columna 5
  titulo:                  Unidad Medida
  tipo:                    t
  nombrecampo:             unimed
  oculta:                  true
  html:                    [size="15", readonly=true ]
6:      # Columna 6
  titulo:                  Existencia
  tipo:                    m
  nombrecampo:             exiart
  oculta:                  true
  html:                    [size="50", readonly=true  ]
7:      # Columna 7
  titulo:                  Cant. Solicitada
  tipo:                    m
  esgrabable:              true
  nombrecampo:             cantot
  esnumerico:              true
  oculta:                  false
  html:                    [size="10"]
8:      # Columna 8
  titulo:                  Cant. a Entregar
  tipo:                    m
  esgrabable:              true
  nombrecampo:             canent
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
9:     # Columna 9
  titulo:                  Cant. Despachada
  tipo:                    m
  esgrabable:              true
  nombrecampo:             candesp
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
10:     # Columna 10
  titulo:                  Precio Precargado
  tipo:                    c
  nombrecampo:             precio
  html:                    [ ]
  esgrabable:              true
11:      # Columna 11
  titulo:                  Precio Editable
  tipo:                    m
  esgrabable:              true
  nombrecampo:             precioe
  esnumerico:              true
  oculta:                  false
  html:                    [size="10" readonly=true]
12:     # Columna 12
  titulo:                  Monto Recargo
  tipo:                    m
  esgrabable:              true
  #oculta:                  true
  nombrecampo:             monrgo
  esnumerico:              true
  html:                    [size="10"]
13:     # Columna 13
  titulo:                  Total
  tipo:                    m
  esgrabable:              true
  nombrecampo:             totart
  esnumerico:              true
  html:                    [size="10"]
14:     # Columna 14
  titulo:                  Cantidad
  tipo:                    m
  esgrabable:              true
  nombrecampo:             distot
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
15:     # Columna 15
  titulo:                  Precio Ant
  tipo:                    m
  esgrabable:              true
  nombrecampo:             preant
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
16:     # Columna 16
  titulo:                  Cant. Entre Art
  tipo:                    m
  esgrabable:              true
  nombrecampo:             canpreart
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
17:     # Columna 17
  titulo:                  Cta. Provee
  tipo:                    t
  esgrabable:              true
  nombrecampo:             codctapro
  oculta:                  true
  html:                    [size="10"]
18:     # Columna 18
  titulo:                  Monto Descuento
  tipo:                    m
  esgrabable:              true
  #oculta:                  true
  nombrecampo:             mondes
  esnumerico:              true
  html:                    [size="10" readonly=true]
19:     # Columna 19
  titulo:                  R
  tipo:                    t
  esgrabable:              true
  nombrecampo:             recar
  oculta:                  true
  html:                    [size="10"]
20:     # Columna 20
  titulo:                  D
  tipo:                    k
  esgrabable:              true
  nombrecampo:             desc
  oculta:                  true
  html:                    [ ]
21:     # Columna 21
  titulo:                  Blanco
  tipo:                    t
  esgrabable:              true
  nombrecampo:             blanco1
  oculta:                  true
  html:                    [size="10"]
22:     # Columna 22
  titulo:                  Blanco2
  tipo:                    m
  esgrabable:              true
  nombrecampo:             blanco2
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
23:       # Columna 23
  titulo:                  N° de Entrega
  tipo:                    t
  nombrecampo:             nronot
  esgrabable:              true
  html:                    [size="10" maxlength=8]
24:       # Columna 24
  titulo:                  N/E Digital
  tipo:                    t
  nombrecampo:             notentdig
  esgrabable:              true
  html:                    ["size=10 maxlength=15"]
25:       # Columna 25
  titulo:                  Orden de Despacho
  tipo:                    t
  nombrecampo:             orddespacho
  esgrabable:              true
  html:                    [size="15" maxlength=8]
26:       # Columna 26
  titulo:                  Guía
  tipo:                    t
  nombrecampo:             guia
  esgrabable:              true
  html:                    [size="15" maxlength=10]
27:       # Columna 27
  titulo:                  Contenedores
  tipo:                    a
  nombrecampo:             contenedores
  esgrabable:              true
  html:                    [size="15x1" maxlength=100]
28:       # Columna 28
  titulo:                  BL
  tipo:                    a
  nombrecampo:             billleading
  esgrabable:              true
  html:                    ["size=15x1 maxlength=100 onBlur='aplicarBL(this.id)'"]
29:       # Columna 29
  titulo:                  Operador de Transporte(OTS)
  tipo:                    t
  nombrecampo:             cedrif
  esgrabable:              true
  html:                    ["size=15 maxlength=15 onBlur='toAjax(6,getUrlModuloAjax(),this.value,0,'&cajtxtmos='+$(this.id).up().next(0).descendants()[0].id+'&rif='+$(this.id).up().next(1).descendants()[0].id+'&nomrif='+$(this.id).up().next(2).descendants()[0].id+'&placa='+$(this.id).up().next(3).descendants()[0].id+'&cajtxtcom='+this.id)'"]
  catalogo:                [faregots, sf_admin_edit_form, {Cedrif: 29, Nomots: 30, Rifpro: 31, Placa: 33}, Faregots_Fafacturpro ]
30:       # Columna 30
  titulo:                  Nombre del OTS
  tipo:                    t
  nombrecampo:             nomots
  esgrabable:              true
  html:                    ["size=40 readOnly=true"]
31:       # Columna 31
  titulo:                  Cooperativa
  tipo:                    t
  nombrecampo:             rifpro
  esgrabable:              true
  html:                    ["size=15 readOnly=true"]
32:       # Columna 32
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             nompro
  esgrabable:              true
  html:                    ["size=40 readOnly=true"]
33:       # Columna 33
  titulo:                  Placa del Chuto
  tipo:                    t
  nombrecampo:             placa
  esgrabable:              true
  html:                    ["size=15 readOnly=true"]
34:       # Columna 34
  titulo:                  Tipo de Viajes
  tipo:                    c
  nombrecampo:             tipov
  esgrabable:              true
  html:                    [ ]
35:       # Columna 35
  titulo:                  Fecha de Salida
  tipo:                    f
  nombrecampo:             fecsal
  esgrabable:              true
  html:                    [size="15" maxlength=20]
36:       # Columna 36
  titulo:                  Hora de Salida
  tipo:                    t
  nombrecampo:             horsal
  esgrabable:              true
  html:                    [size="15" maxlength=20]
37:       # Columna 37
  titulo:                  Fecha de Llegada CA
  tipo:                    f
  nombrecampo:             fecllca
  esgrabable:              true
  html:                    [size="15" maxlength=20]
38:       # Columna 38
  titulo:                  Hora de Llegada CA
  tipo:                    t
  nombrecampo:             horllca
  esgrabable:              true
  html:                    [size="15" maxlength=20]
39:       # Columna 39
  titulo:                  Fecha de Descarga
  tipo:                    f
  nombrecampo:             fecdesc
  esgrabable:              true
  html:                    [size="15" maxlength=20]
40:       # Columna 40
  titulo:                  Hora de Descarga
  tipo:                    t
  nombrecampo:             hordesc
  esgrabable:              true
  html:                    [size="15" maxlength=20]
41:       # Columna 41
  titulo:                  Fecha de Llegada
  tipo:                    f
  nombrecampo:             feclleg
  esgrabable:              true
  html:                    [size="15" maxlength=20]
42:       # Columna 42
  titulo:                  Hora de Llegada
  tipo:                    t
  nombrecampo:             horlleg
  esgrabable:              true
  html:                    [size="15" maxlength=20]
43:       # Columna 43
  titulo:                  Producto
  tipo:                    t
  nombrecampo:             codprod
  esgrabable:              true
  html:                    ["size=15 maxlength=8 onBlur='toAjax(8,getUrlModuloAjax(),this.value,0,'&cajtxtmos='+$(this.id).up().next(0).descendants()[0].id+'&cajtxtcom='+this.id)'"]
  catalogo:                [fadefpro, sf_admin_edit_form, {Codprod: 43, Desprod: 44}, Fadefpro_Fafacturpro ]
44:       # Columna 44
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desprod
  esgrabable:              true
  html:                    ["size=40 readOnly=true"]
45:       # Columna 45
  titulo:                  Origen KG
  tipo:                    m
  nombrecampo:             kg
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
46:       # Columna 46
  titulo:                  KG Entregados
  tipo:                    m
  nombrecampo:             kgent
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
47:       # Columna 47
  titulo:                  Diferencia KG
  tipo:                    m
  nombrecampo:             difkg
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 readOnly=true"]
48:       # Columna 48
  titulo:                  Cajas Origen
  tipo:                    m
  nombrecampo:             cajas
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
49:       # Columna 49
  titulo:                  Cajas Entregadas
  tipo:                    m
  nombrecampo:             cajasent
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
50:       # Columna 50
  titulo:                  Diferencia Cajas
  tipo:                    m
  nombrecampo:             difcaj
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 readOnly=true"]
51:       # Columna 51
  titulo:                  Toneladas
  tipo:                    m
  nombrecampo:             tm
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
52:       # Columna 52
  titulo:                  Toneladas Entregadas
  tipo:                    m
  nombrecampo:             tment
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 onBlur='ValidarMontoGridv2(this); calculardif(this.id);'"]
53:       # Columna 53
  titulo:                  Diferencia Toneladas
  tipo:                    m
  nombrecampo:             difton
  esgrabable:              true
  esnumerico:              true
  html:                    ["size=15 readOnly=true"]
54:       # Columna 54
  titulo:                  IER
  tipo:                    t
  nombrecampo:             ier
  esgrabable:              true
  html:                    ["size=15 maxlength=15"]
55:       # Columna 55
  titulo:                  Estatus
  tipo:                    c
  nombrecampo:             estatus
  esgrabable:              true
  html:                    [ ]
56:       # Columna 56
  titulo:                  Observaciones
  tipo:                    t
  nombrecampo:             observaciones
  esgrabable:              true
  html:                    [ size="80" maxlength=500 ]
  catalogo:                [faobservafac, sf_admin_edit_form, {Obsfac: 56}, Faobservafac_Fafacturpro ]
57:       # Columna 57
  titulo:                  N° Factura Asociada
  tipo:                    t
  nombrecampo:             numfac
  esgrabable:              true
  html:                    ["size=15 readOnly=true"]
58:       # Columna 58
  titulo:                  Estatus verdadero
  tipo:                    t
  nombrecampo:             estatus2
  esgrabable:              true
  oculta:                  true
  html:                    ["size=15 readOnly=true"]