generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cadphart
    theme:            cidesaGenerator
    fields:
      dphart: { name: Número}
      fecdph: { name: Fecha}
      codalm: { name: Código de Almacén}
      nomalm: { name: Nombre Almacén}
      reqart: { name: Referencia}
      desreq: { name: Descripción}
      fecreq: { name: Fecha de Requisión}
      desdph: { name: Descripción}
      codori: { name: Unidad de Origen}
      nomcat: { name: Descripción}
      mondph: { name: Monto Total}
      stadph: { name: Estatus}
      numcom: { name: Numerocom}
      refpag: { name: refpago}
      tipdph: { name: Tipodesp}
      codcli: { name: codigo}
      obsdph: { name: Observacion}
      fordesp: { name: fordes}
      reapor: { name: reapor}
      fecanu: { name: fechaanu}
      codubi: { name: Código de la Ubicación}
      nomubi: { name: Nombre Ubicación}
      tipref: { name: Refiere a}
      codpro: { name: CI/RIF Cliente}
      rifpro: { name: RIF}
      nompro: { name: Nombre}
      dirpro: { name: Dirección}
      telpro: { name: Teléfono}
      fecemiov: { name: Fecha Emisión}
      feccarov: { name: Fecha de Carga}
      locori:   { name: Localidad Despachadora de la Mercancia en Origen }
      direccion: { name: Dirección}
      rubro:     { name: Rubro}
      cankg:     { name: Cantidad Total en KG/UNID}
      totpasreal: { name: Totales Paso Real 397RL.}
      locrec:    { name: Localidad Receptora de la Mercancia en Destino}
      emptra:    { name: Empresa Transportista}
      nomrep:    { name: Nombre del Representante}
      telemp:    { name: Telefonos}
      choveh:    { name: Chofer del Vehículo}
      cedcho:    { name: C.I}
      telcho:    { name: Telefono}
      nomconfordes: { name: Apellidos  y Nombres}
      cedconfordes: { name: C.I}
      horsalconfordes: { name: Hora Salida}
      nomconforrec: { name: Apellidos y Nombres}
      cedconforrec: { name: C.I}
      horlleconforrec: { name: Hora Llegada}

    list:
      title:          Despachos
      filters:        [dphart]
      display:        [=dphart, desdph, fecdph]
      fields:
        fecdph: { params: date_format='dd/MM/yy' }
      object_actions:
        _edit:        ~
        _delete:        ~
      max_per_page:   10
      sort:    dphart
    edit:
      title:          Edicion de Despachos
      display:
        "Datos del Despacho": [dphart, fecdph, codpro, rifpro, dirpro, telpro, codalm, nomalm, tipref, reqart, desreq, fecreq, desdph, codori, nomcat, mondph, stadph, numcom, refpag, tipdph, codcli, obsdph, fordesp, reapor, fecanu, codubi, nomubi]
        Datos Orden de Despacho Vehicular: [fecemiov, feccarov, locori, direccion, rubro, cankg, totpasreal, locrec, emptra, nomrep, telemp, choveh, cedcho, telcho, nomconfordes, cedconfordes, horsalconfordes, nomconforrec, cedconforrec, horlleconforrec]
      fields:
        fecdph: { params: date_format='dd/MM/yy' }
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~