generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Citiping
    theme:            default
    fields:
      codtip:     { name : Código }
      destip:     { name : Descripción }
    list:
      title:          Tipos de Ingresos
      display:        [=codtip, destip]
      filters:		  [codtip, destip]
      max_per_page:	  5
      object_actions:
        _edit:        ~
        _delete:      ~
      
    edit:
      title:          Edición de Tipos de Ingresos
      display:        [codtip, destip]