generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Litiplic
    theme:            cidesaGenerator
    fields:
       codtiplic:    { name: Número Memorando, params: size=10 maxlength=8 onBlur="this.value=this.value.pad(4,'0',0)"}
       destiplic:    { name: Descripción, params: size=60 maxlength=500}
       maxunitri:    { name: Máximo de Unidades Tributarias}
       artley:       { name: Artículo de Ley, type: textarea_tag, params: size=70x3 maxlength=1000 }
       canunitribie: { name: Cantidad Unidades Tributarias Bien/Servicio}
       canunitriobr: { name: Cantidad Unidades Tributarias Obra}
    list:
      title:  Modalidad de Contratación
      display: [=codtiplic, destiplic]
      filters: [ codtiplic, destiplic]
      max_per_page:   10
      sort: destiplic
      object_actions:
        _edit:        ~
        _delete:      ~
    edit:
      title: Modalidad de Contratación
      display:
        "NONE": [codtiplic, destiplic, maxunitri, artley, canunitribie, canunitriobr]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~