generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cideftit
    theme:            cidesaGenerator
    fields:
      codpre: { name: Código}
      nompre: { name: Nombre}
      codcta: { name: Código}
      descta: { name: Nombre}
      #stacod: { name: Estatus}
      #coduni: { name: Código de Unidad}
      #estatus: { name: Estatus2}

    list:
      title:          Titulos Presupuestarios
      filters:        [codpre, nompre ]
      display:        [=codpre, nompre]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
      sort:  codpre
    edit:
      title:          Edicion de Titulos Presupuestarios
      display:
        Datos del Título Presupuestario: [ _codpre, nompre ]
        Datos Contables: [ _codcta ]
      hide:  [ mascara ]
      actions:
        _list:        ~
        _create:      ~
        _save:        ~
        _delete:      ~