generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Fcconrep
    theme:            cidesaGenerator
    fields:
      rifcon:  { name: C.I./R.I.F, params: size=13 maxlength=11}
      nitcon:  { name: N.I.T, params: size=22 maxlength=20}
      nomcon:  { name: Nombre / Razón Social, params: size=40 maxlength=255}
      repcon:  { name: Tipo , params: size=40 maxlength=1}
      dircon:  { name: Dirección , params: size=40 maxlength=255}
      telcon:  { name: Teléfono, params: size=32 maxlength=30}
      emacon:  { name: Email , params: size=52 maxlength=50}
      codsec:  { name: Código, params: size=8 maxlength=4}
      codpar:  { name: Parroquia , params: size=6 maxlength=4}
      codmun:  { name: Municipio , params: size=6 maxlength=4}
      codedo:  { name: Estado , params: size=6 maxlength=4}
      codpai:  { name: Pais , params: size=6 maxlength=4}
      #ciucon:  { name: Ciudad, params: size=13 maxlength=30}
      cpocon:  { name: Código Postal, params: size=22 maxlength=6}
      apocon:  { name: Cod. Apartado Postal , params: size=40 maxlength=20}
      urlcon:  { name: URL , params: size=40 maxlength=50}
      naccon:  { name: Nacionalidad , params: size=40 maxlength=1}
      tipcon:  { name: Tipo de Persona , params: size=32 maxlength=1}
      faxcon:  { name: Porcentaje , params: size=52 maxlength=15}
      clacon:  { name: Código, params: size=8 maxlength=12}
      fecdescon:  { name: . , params: date_format='dd/MM/yyyy' }
      fecactcon:  { name: . , params: date_format='dd/MM/yyyy' }
      stacon:  { name: . , params: size=6 maxlength=1}
      origen:  { name: Alicuota [X/1000], params: size=6 maxlength=1}
      nomneg:  { name: Año, params: size=6 maxlength=255}
      reccon:  { name: Año, params: size=6 maxlength=100}
      tem:  { name: Año, params: size=10 maxlength=8}
      grid: { name: . , params: size=10 maxlength=8}
    list:
      title:     Datos del Contribuyente
      display:   [ =rifcon, nomcon]
      sort:      nomcon
      filters:   [rifcon, nomcon]
      fields:
        nomcon:
          params: size=10
        rifcon:
          params: size=10
      max_per_page: 5
      object_actions:
        _edit:        ~
        _delete:      ~
      sort:  cedcon
    edit:
      title:          Edición Datos del Contribuyente
      display:
        "Datos Generales":   [ rifcon, nitcon, nomcon, _naccon, _tipcon, _repcon ]
        #"Nacionalidad":   [  ]
        #"Tipo":   [ _tipcon ]
        "Datos Personales":   [ dircon, _codpar, cpocon, apocon, telcon, emacon, faxcon, urlcon ]
        "Recaudos Consignados":   [ _grid ]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~