generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Npantpre
    theme:            default
    fields:
      codemp: { name: Codigo}
      nomemp: { name: Nombre}
      monant: { name: Antiguedad Acumulada}
      fecant: {name: Fecha del Anticipo}
      observacion: { name: Observacion}
      monto: { name: Monto del Anticipo}
      fecsolant: { name: Fecha Solicitud Anticipo}

    list:
      title:          Anticipo Sobre Prestaciones
      filters:        [codemp]
      display:        [=codemp, nomemp, fecant]
      fields:
        fecant: { params: date_format='dd/MM/yy' }
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
    edit:
      title:          Edici√≥n Anticipo Sobre Prestaciones
      display:       [=codemp, nomemp, monant, fecsolant, fecant, monto, observacion]
      fields:
        fecant: { params: date_format='dd/MM/yy' }
      actions:
        _list:        ~
        _save:         ~
        _create:       ~