default:
  http_metas:
    content-type: text/html

  metas:
    title:        Documentos Financieros
    robots:       index, follow
    description:  MÃ³dulo de Documentos Financieros
    keywords:     documentos financieros
    language:     en

  stylesheets:    [main, estilos]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, tools, observe,  prototype_1_5_1]

  has_layout:     on
  layout:         layout
