default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo Bienes Nacionales
    robots:       index, follow
    description:  Módulo Bienes Nacionales
    keywords:     Módulo, Bienes, Nacionales
    language:     en

  stylesheets:    [main, estilos]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax ]

  has_layout:     on
  layout:         layout
