generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Npcargos
    theme:            cidesaGenerator
    fields:
      display:        [ codnom ]
      codnom:         { name: NÃ³mina}
      tipnom:         { name: .}
      gridcargos:     { name: .}
      cantidad:       { name: Aumentar por Cantidad}
      porcentaje:     { name: Aumentar por Porcentaje}
      fecaum:     { name: Fecha}
      motaum:     { name: Motivo, params: size=80 maxlength=250 disabled=false}
    edit:
      title:      Aumento de Sueldos por Cargos
      fields:
        cantidad:                    {params: disabled=false onBlur="mientermontootro(event,this.id);aumentosuecar(this.value,1);"}
        porcentaje:                  {params: disabled=false onBlur="aumentosuecar(this.value,2);" maxlength=3 size=5}
      display:
        Datos para el Aumento:       [_tipnom, cantidad, porcentaje, _fecaum, motaum]
        Listado de Cargos:           [_gridcargos]
        
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
