generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Catcosaval
    theme:            cidesaGenerator
    fields:
      coddivgeo: { name: Ubicacion Geografica, params: size=30 maxlength=30}
      desdivgeo: { name: Descripción }
      tipo: { name: Tipo }
      destipo: { name: Tipo }
      desuso: { name: Uso Inmueble}
      catusoesp_id: { name: Uso Inmueble, params: include_custom= "Seleccione" }
      costo: { name: Costo en Mt2, params: onBlur="event.keyCode=13; formatoDecimal(event,this.id);" }

    list:
      title: Costos para Avalúo
      display: [=coddivgeo, desdivgeo, destipo, desuso]
      filters: [coddivgeo]
      object_actions:
       _edit:        ~
       _delete:      ~
      max_per_page:	  10
      sort:    coddivgeo

    edit:
      title: Edición de Costo por Avalúo
      display:
        "NONE": [_coddivgeo, _tipo, catusoesp_id, costo]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      ~