opciones:                  # Opciones generales
  name:                    b
  eliminar:                false
  tabla:                   fcdefpgi
  anchogrid:               800
  ancho:                   700
  filas:                   0
  titulo:                  'Distribucion de la Deuda'
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Nro
  tipo:                    t
  nombrecampo:             numero
  html:                    [size="5"]
  oculta:                  false
  esgrabable:              true
2:       # Columna 2
  titulo:                  Vencimiento
  tipo:                    f
  nombrecampo:             fecven
  html:                    [size="10"]
  esgrabable:              true
3:       # Columna 3
  titulo:                  Descripcion de la Cuota
  tipo:                    a
  nombrecampo:             nombre
  html:                    [size="30x2" ]
  esgrabable:              true
4:       # Columna 4
  titulo:                  Tipo
  tipo:                    t
  nombrecampo:             tipo
  html:                    [size="10"]
  esgrabable:              true
5:       # Columna 5
  titulo:                  Monto Cuota
  tipo:                    m
  nombrecampo:             mondec
  html:                    [size="10" onBlur=validaMontos(this.id,this);]
  esgrabable:              true
6:       # Columna 6
  titulo:                  Estado de la Deuda
  tipo:                    t
  nombrecampo:             edodecstatus
  html:                    [size="20" ]
  esgrabable:              true