opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   formetotrcre
  anchogrid:               1000
  ancho:                   1000
  filas:                   
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Cod. Meta
  tipo:                    t
  nombrecampo:             codact
  html:                    ["size=15 readonly=true"]
  esgrabable:              true  
2:       # Columna 2
  titulo:                  Descripci贸n
  tipo:                    t
  nombrecampo:             desact
  html:                    ["size=40 readonly=true"]
  esgrabable:              true
3:       # Columna 3
  titulo:                  Cantidad
  tipo:                    m
  esgrabable:              true
  nombrecampo:             canact
  esnumerico:              true
  html:                    ["size=10"]
4:       # Columna 4
  titulo:                  Partida
  tipo:                    t
  nombrecampo:             codparegr
  html:                    ["size=15 "]
  esgrabable:              true  
5:       # Columna 5
  titulo:                  Descripci贸n
  tipo:                    t
  nombrecampo:             nomparegr
  html:                    ["size=40 readonly=true"]
6:       # Columna 6
  titulo:                  Monto
  tipo:                    m
  esgrabable:              true
  nombrecampo:             monpre
  esnumerico:              true
  html:                    ["size=10 onBlur='mostrarperiodos(this.id)' readOnly=true"]
7:       # Columna 7
  titulo:                  Fuente de Financiamiento
  tipo:                    t
  nombrecampo:             codfin
  html:                    ["size=10 onBlur='mostrarfinanciamientos(this.id)' readonly=true"]
  esgrabable:              true
8:       # Columna 8
  titulo:                  Descripci贸n
  tipo:                    t
  nombrecampo:             nomparing
  html:                    ["size=40 readonly=true"]
  esgrabable:              true
9:       # Columna 9
  titulo:                  Cod. Org
  tipo:                    t
  nombrecampo:             codorg
  html:                    ["size=10 onBlur='mostrarorganismos(this.id)' readonly=true"]
  esgrabable:              true
10:       # Columna 10
  titulo:                  Nombre Organismo
  tipo:                    t
  nombrecampo:             nomorg
  html:                    ["size=40 readonly=true"]
  esgrabable:              true
11:       # Columna 11
  titulo:                  Tipo de Gasto
  tipo:                    t
  nombrecampo:             codtip
  html:                    ["size=10 maxlength=4 onBlur='toAjax(4,getUrlModuloAjax(),this.value,0,'&cajtexmos='+$(this.id).up().next(0).descendants()[0].id+'&cajtexcom='+this.id)'"]
  esgrabable:              true
  catalogo:                [fortiptit, sf_admin_edit_form, {Codtip: 11, Destip: 12}, Fortiptit_Forpoa ]
12:       # Columna 12
  titulo:                  Descripci贸n
  tipo:                    t
  nombrecampo:             destip
  html:                    ["size=40 readonly=true"]
  esgrabable:              true
13:       # Columna 13
  titulo:                  Observaciones
  tipo:                    t
  nombrecampo:             observ
  html:                    ["size=40 maxlength=250 "]
  esgrabable:              true
14:       # Columna 14
  titulo:                  cadenaperiodos
  tipo:                    t
  nombrecampo:             cadenaper
  html:                    ["size=40"]
  esgrabable:              true
  oculta:                  true
15:       # Columna 15
  titulo:                  Cadena Fuente Financiamiento
  tipo:                    t
  nombrecampo:             cadenafin
  html:                    ["size=40"]
  esgrabable:              true
  oculta:                  true
16:       # Columna 16
  titulo:                  Cadena Organismos
  tipo:                    t
  nombrecampo:             cadenaorg
  html:                    ["size=40"]
  esgrabable:              true
  oculta:                  true