default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo de Compras
    robots:       index, follow
    description:  Módulo de Compras
    keywords:     Módulo de Compras
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax ]
#  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, ext/adapter/ext/ext-base, ext/adapter/prototype/ext-prototype-adapter, ext/ext-all, gridext.js]

#ext/adapter/ext/ext-base, ext/adapter/prototype/ext-prototype-adapter, ext/ext-all
  has_layout:     on
  layout:         layout