generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Atpresupuesto
    theme:            cidesaGenerator

    fields:
      atayudas_id:      { name: Nro. Expediente/Solicitud }

      atprovee1:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro1" getsecundario="getNompro1" campoprincipal="rifpro1" camposecundario="nompro1" campobase = "atprovee1"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:
      monto1:         { name: Monto }

      atprovee2:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro2" getsecundario="getNompro2" campoprincipal="rifpro2" camposecundario="nompro2" campobase = "atprovee2"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:
      monto2:         { name: Monto }
      
      atprovee3:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro3" getsecundario="getNompro3" campoprincipal="rifpro3" camposecundario="nompro3" campobase = "atprovee3"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:
      monto3:         { name: Monto }
      
      atprovee4:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro4" getsecundario="getNompro4" campoprincipal="rifpro4" camposecundario="nompro4" campobase = "atprovee4"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:
      monto4:         { name: Monto }

      atprovee5:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro5" getsecundario="getNompro5" campoprincipal="rifpro5" camposecundario="nompro5" campobase = "atprovee5"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:
      monto5:         { name: Monto }
      
      atprovee6:
        name: Proveedor
        catalogo:  
          catalogoweb: Atprovee_Aciprovee
          clase: Atprovee
          ajax: 1
          parametros: getprincipal="getRifpro6" getsecundario="getNompro6" campoprincipal="rifpro6" camposecundario="nompro6" campobase = "atprovee6"
          catalogoparams: campo1/rifpro/campo2/nompro
          #ajaxparams:  
          divupdate: divgridprovee
          #id:

      monto6:         { name: Monto }
      

    list:
      title:          Registro de Presupuestos
      display:        [=atayudas_id, nomsolben]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [atayudas_id]
      max_per_page:   10
    edit:
      title:          Edici√≥n de Presupuestos
      display:
        Datos de Expediente/Solicitud: [_expediente]
        Presupuesto Consignado: [atprovee1, monto1, atprovee2, monto2, atprovee3, monto3]
        Presupuesto por OGAS: [atprovee4, monto4, atprovee5, monto5, atprovee6, monto6]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
