generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Liregofe
    theme:            cidesaGenerator
    fields:
      ente:           { name: Ente Contratante, params: readonly=true size=60 style=border:none}
      codempadm:
        name: Para
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 2
          parametros: getprincipal="getCodempadm" getsecundario="getNomempadm" campoprincipal="codempadm" camposecundario="nomempadm" campobase = "id"
      nomcaradm:      { name: Cargo, params: style=border:none}
      coduniadm:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 3
          parametros: getprincipal="getCoduniadm" getsecundario="getDesuniadm" campoprincipal="coduniadm" camposecundario="desuniadm" campobase = "id"
      codempeje:
        name: De
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_codemp
          clase: Lidatste
          ajax: 4
          parametros: getprincipal="getCodempeje" getsecundario="getNomempeje" campoprincipal="codempeje" camposecundario="nomempeje" campobase = "id"
      nomcareje:      { name: Cargo, params: style=border:none}
      coduniste:
        name: Unidad
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Lidatste_licregsol
          clase: Lidatste
          ajax: 5
          parametros: getprincipal="getCoduniste" getsecundario="getDesuniste" campoprincipal="coduniste" camposecundario="desuniste" campobase = "id"
      numofe:         { name: Número Oferta, params: size=10 maxlength=8 onBlur=Correl(this.id) }
      numexp:
        name: No Expedientes
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Liplieesp_numexp
          clase: Liplieesp
          ajax: 1
          parametros: getprincipal="getNumexp" getsecundario="getDesnumexp" campoprincipal="numexp" camposecundario="desnumexp" campobase = "id"
          divupdate:  divgridart
      numplie:        { name: Número de Pliego }
      ejepre:         { name: Ejercicio Prespuestario Año}
      desclacomp:     { name: Solicitud de Compra, params: style="border:none" size=80}
      destiplic:      { name: Modalidad de Contratación, params: style="border:none" size=80}
      tipcom:         { name: Compra, params: style="border:none" size=80}
      tipcon:         { name: Bienes/servicios, params: style="border:none" size=80}
      codpro:
        name: Empresa Solicitante
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Liempofe_codpro
          clase: Caprovee
          ajax: 7
          parametros: getprincipal="getCodpro" getsecundario="getNompro" campoprincipal="codpro" camposecundario="nompro" campobase = "id"
          catalogoparams: /param1/'."'+$('liregofe_numexp').value+'".'
      rif:            { name: R.I.F, params: readonly=true style=border:none}
      nomrepleg:      { name: Representante Legal, params: readonly=true style=border:none size=80}
      codtipemp:
        name: Tipo de Empresa
        msj_error: El Código es necesario
        catalogo:
          catalogoweb: Litipemp_codemp
          clase: Litipemp
          ajax: 0
          parametros: getprincipal="getCodtipemp" getsecundario="getDestipemp" campoprincipal="codtipemp" camposecundario="destipemp" campobase = "id"
      fecreg:         { name: Fecha Registro, params: onChange=CalculaFecha(this.value)}
      dias:           { name: Dias para el Vencimiento, params: onChange=CalculaFecha(this.value)}
      fecven:         { name: Fecha Vencimiento, params: readonly=true style=border:none}
      ofenro:         { name: Oferta No., params: size=10 maxlength=8 }
      fecofe:         { name: Fecha Oferta}
      monofe:         { name: Monto Oferta, params: readonly=true style=border:none }
      monrecofe:      { name: Monto Recargos, params: readonly=true style=border:none }
      porvan:         { name: Porcentaje (%) }
      declar:         { name: Declaración Jurada de Auto Cálculo del Valor Agregado Nacional (VAN), type: checkbox_tag }
      espacio:        { name: . , params: readonly=true style=border:none}
      gridart:        { name: .}
      gridrgo:        { name: .}
      gridforpag:     { name: .}
      gridcroent:     { name: .}
      gridleg:        { name: .}
      gridtec:        { name: .}
      gridfin:        { name: .}
      gridfia:        { name: .}
      docane1:
        name:  Documento Anexo 1
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 1***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane2:
        name:  Documento Anexo 2
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 2***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane3:
        name:  Documento Anexo 3
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 3***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      docane4:
        name:  Documento Anexo 4
        type:  admin_input_file_tag
        params:  include_link=assets include_text="*********Anexo 4***********" include_remove=true
        upload_dir:  assets
        help:       Favor cargar solo archivos con extension (pdf,doc,ppt)
      prepor:         { name: Preparado Por, params: size=80 }
      preporcar:      { name: Cargo, params: size=80 }
      lisicact_id:    { name: Declaratoria Modalidad, params: include_blank="Seleccione..." }
      detdecmod:      { name: Detalle Declaratoria Modalidad, type: textarea_tag, params: size="80x10" }
      anapor:         { name: Preparado Por, params: size=80 }
      anaporcar:      { name: Cargo, params: size=80 }
      js:             {name: .}

    list:
      title:           Registro de Ofertas
      display:         [=numofe, numplie, numexp, desuniadm, desuniste, fecreg ]
      filters:         [numofe, numplie, numexp, coduniadm, coduniste, fecreg]
      fields:
        desuniadm:     { name: Para}
        desuniste:     { name: De}
      object_actions:
        _edit:          ~
        _delete:        ~
      max_per_page:    10
      sort:            numofe

    edit:
      title:           Registro de Ofertas
      display:
        Datos Generales:    [ente, codempadm, nomcaradm, coduniadm, codempeje, nomcareje, coduniste, numofe, numexp, numplie, ejepre, destiplic, desclacomp, tipcom, tipcon, codpro, rif, nomrepleg, codtipemp, fecreg, dias, fecven]
        Bienes o Servicio a Adquirir: [ofenro, fecofe, _gridart, monofe]
        Otros Recargos por Facturas: [_gridrgo, monrecofe]
        Formas de Pago: [_gridforpag]
        Cronograma de Entregas:  [_gridcroent]
        Documentos Entregados:   [_gridleg, _gridtec, _gridfin, _gridfia]
        Valor Agregado Nacional: [porvan, declar, espacio]
        Otros:  [docane1, docane2, docane3, docane4]
        Delcaratoria: [prepor, cargopre, lisicact_id, detdecmod, anapor, cargoana, _js]
      fields:
        numexp:       {params: readonly=true style=border:none}
        numplie:      {params: readonly=true style=border:none}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~