opciones:                  # Opciones generales
  name:                    h
  eliminar:                false
  tabla:                   Liregofefia
  anchogrid:               900
  ancho:                   850
  filas:                   0
  titulo:                  ' Fianzas/Garantias'
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Criterio
  tipo:                    t
  nombrecampo:             codcomres
  html:                    [ size=10 readonly=true ]
  esgrabable:              true
2:
  titulo:                  Descripci√≥n
  tipo:                    t
  nombrecampo:             descomres
  html:                    [ size=20 readonly=true ]
  esgrabable:              false
3:
  titulo:                  Si/No
  tipo:                    k
  nombrecampo:             check
  html:                    [  ]
  esgrabable:              true
4:
  titulo:                  Limitante
  tipo:                    t
  nombrecampo:             limit
  html:                    [ readonly=true size=10 ]
  esgrabable:              false
5:
  titulo:                  Observaciones
  tipo:                    t
  nombrecampo:             observ
  html:                    [ size=40 ]
  esgrabable:              true
