generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Npcomocp
    theme:            default
    fields:
      pascar:    { name: Nro. Pasos, params: maxlength=3 }
      gracar:    { name: Grado, params: maxlength=3 }
      suecar:    { name: Paso 1 }
      codtipcar: { name: Cod. Tipo Cargo, params: maxlength=3 }
      fecdes:    { name: Vigencia, params: date_format='dd/MM/yyyy'}
    list:
      title:          Tablas de Sueldos por Tipo de Cargos
      filters:        [codtipcar, fecdes]
      display:        [=codtipcar, fecdes]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:  8
      codtipcar:    ordcom
    edit:
      title:          Edicion de Tablas de Sueldos por Tipo de Cargos
      display:        [codtipcar, pascar, fecdes, ]
      actions:
        _list:         ~
        _save:         ~
        _create        ~