generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Facliente
    theme:            cidesaGenerator

    fields:
      codpro:       { name : Código}
      nompro:       { name : Nombre}
      rifpro:       { name : C.I./RIF}
      nitpro:       { name : NIT}
      dirpro:       { name : Dirección}
      telpro:       { name : Teléfono}
      nrocei:       { name : Nro.RNC}
      email:        { name : Correo Electrónico}
      pagweb:       { name : Página Web}
      codram:       { name : Ramo}
      nomram:       { name : Nombre del Ramo}
      limcre:       { name : Limite de Crédito}
      codcta:       { name : Cta. Contable Asoc.}
      descta:       { name : Descripción}
      codord:       { name : Cta. de Orden Asoc.}
      desctacodord: { name : Descripción}
      codpercon:    { name : Cta.PerContra Asoc.}
      desctacodpercon: { name : Descripción}
      fecinscir:    { name : Fecha de Registro}
      faxpro:       { name : Fax}
      numinscir:    { name : Circunscripción Judicial}
      regmer:       { name : Registro Mercantil}
      tomreg:       { name : Tomo}
      capsus:       { name : Capital Suscrito}
      fecreg:       { name : Fecha Reg}
      folreg:       { name : Folio}
      cappag:       { name : Capital Pagado}
      fecven:       { name : Fecha Venc}
      rifrepleg:    { name : C.I./R.I.F.}
      nomrepleg:    { name : Nombre}
      dirrepleg:    { name : Dirección}
      telrepleg:    { name : Teléfono}
      correpleg:    { name : Correo}
      rifpercon:    { name : C.I./R.I.F.}
      nompercon:    { name : Nombre}
      dirpercon:    { name : Dirección}
      telpercon:    { name : Teléfono}
      corpercon:    { name : Correo}
      codtiprec:    { name : Grupo}
      destiprec:    { name : Descripción}
      nacpro:       { name : Nacionalidad}
      tipo:         { name : Actividad Principal}
      codctasec:    { name : Cta. Contable Asoc}
      desctacodctasec:    { name : Descripción}
      codordadi:          { name : Cta. de Orden Asoc}
      desctacodordadi:    { name : Descripción}
      codperconadi:       { name : Cta. PerContra Asoc}
      desctacodperconadi: { name : Descripción}
      codordmercon:       { name : Cta. de Orden}
      desctacodordmercon: { name : Descripción}
      codpermercon:       { name : Cta. PerContra}
      desctacodpermercon: { name : Descripción}
      codordcontra:       { name : Cta. de Orden}
      desctacodordcontra: { name : Descripción}
      codpercontra:       { name : Cta. PerContra}
      desctacodpercontra: { name : Descripción}
      recargo:            { name : Recaudos}
      codtipemp:          { name : Tipo de Empresa}
      destip:             { name : Descripción}
      fatipcte_id:        { name : Tipo de Cliente}
      tipper:             { name : Tipo de Persona}
      escontrib:             { name : Es Contribuyente}
      codedo:             { name : Estado}

    list:
      title:          Registro de Cliente
      display:        [=codpro, nompro, rifpro]
      filters:		  [codpro, nompro, rifpro]
      max_per_page:	  10
      sort:           codpro
      fields:
        codpro:      { params : maxlength=8 }
      object_actions:
        _edit:        ~
        _delete:      ~

    edit:
      title:          Edición de Cliente
      display:        [codpro, nompro, rifpro, fatipcte_id, nitpro, dirpro, telpro, nrocei, email, pagweb, codram, nomram, limcre, codcta, descta, codord, desctacodord, codpercon, desctacodpercon, fecinscir, faxpro, numinscir, regmer, tomreg, capsus, fecreg, folreg, cappag, fecven, rifpercon, nompercon, dirpercon, telpercon, corpercon, rifrepleg, nomrepleg, dirrepleg, telrepleg, correpleg, codtiprec, destiprec, nacpro, tipo, codctasec, desctacodctasec, codordadi, desctacodordadi, codperconadi, desctacodperconadi, codordmercon, desctacodordmercon, codpermercon, desctacodpermercon, codordcontra, desctacodordcontra, codpercontra, desctacodpercontra, recargo, codtipemp, destip, escontrib, codedo]
      fields:
        recargo:    { type: admin_double_list, params: through_class=Farecpro}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
