generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Npasiconemp
    theme:            default
    fields:
      codemp:       { name: Codigo Empleado, params: maxlength=10,size=10  }
      nomemp:       { name: Nombre empleado }
      codcar:       { name: Codigo Cargo, params: size=20  }
      nomcar:       { name: Nombre del Cargo }
      codnom:       { name: Codigo Nomina }
      nomnom:       { name: Nomina }
      nomcon:       { name: Concepto: }
      monto:        { name: Monto }
      cantidad:     { name: Cantidad }
      codcon:		{ name: CÃ³digo Concepto }
    list:
      title:          Movimientos por Concepto
      display:        [=codcon, nomcon, codnom, nomnom]
      filters:		  [codcon, codnom]
      max_per_page:	  10
      object_actions:
        _edit:        ~
        _delete:      ~

    edit:
      title:          Movimientos por Concepto
      display:        [codcon, codemp, nomemp, codcar, nomcar, monto, cantidad]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
