generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Npvacdiafer
    theme:            default
    fields:
      descripcion: { name: Descripción }
      dia: { name: Día, params: maxlength=2}
      mes: { name: Mes, params: maxlength=2 }
    list:
      title:          Definición de Días Feriados
      filters:        [descripcion, mes ]
      display:        [=descripcion, dia, mes ]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
      sort: mes
    edit:
      title:          Edición de Días Feriados
      actions:
        _save:        ~
        _create:      ~