generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Dfatendoc
    theme:            cidesaGenerator
    fields:
      coddoc:         { name : Código }
      desdoc:         { name : Descripción, type: textarea_tag, params: size=60x3 }
      staate:         { name : Estatus }
      anuate:         { name : Estado Atencion }
      estado:         { name : Documento }
      id_dftabtip:    { name : Tipo Documento, params: include_custom=Seleccione... }
      desate:         { name : Descripción de la Atención }
      infdoc1:        { name : Inf. Adicional 1 }
#      destra:         { name : Descripción del medio de transporte }
#      desate:         { name : Descripción de la Atención/Observación }
#      diaent:         { name : Dias de Entregas }
#      id_dfmedtra:    { name : Medio de Transporte }

    edit:
      title:          Atención de Documentos
      display:        
        Filtro:      [ id_dftabtip, _staate, _anuate, desdoc ]
        Documentos:  [ _grid ]
      actions:
        filtro:      { name: Filtrar, action: edit }
        _save:        ~
