opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   fcapulicdet
  ancho:                   250
  anchogrid:               400
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '

1:       # Columna 1
  titulo:                  CÃ³digo
  tipo:                    t
  nombrecampo:             tipvar
  esgrabable:			   true
  html:                    [size="25", readonly=true]
2:       # Columna 2
  titulo:                  Valor
  tipo:                    m
  nombrecampo:             valor
  esgrabable:			   true
  html:                    [size="15"]
