generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Npnomina
    theme:            default
    fields:
      codnom: { name: C贸digo }
      nomnom: { name: Nombre }
      frecal: { name: Frecuencia de Pago }
      ultfec: { name: Desde, params: date_format='dd/MM/yyyy' }
      profec: { name: Hasta, params: date_format='dd/MM/yyyy' }
      numsem: { name: Semana Nro }
      ordpag: { name: Genera Orden de Pago }

    list:
      title:          Tipos de N贸mina
      filters:        [codnom, nomnom ]
      display:        [=codnom, nomnom, ultfec, profec]
      sort:  codnom
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
      sort: codnom
    edit:
      title:         Edici贸n de Tipos de N贸mina
      display:       [codnom, nomnom, frecal, ultfec, profec, numsem, ordpag]
      actions:
        _list:       ~
        _save:       ~
        _create:     ~
        _delete:     ~
